### ISSUE TITLE
[M3] @EnableDiscoveryClient fails without explicit @Import of ConsulAutoConfiguration

### ISSUE THREAD

**Issue by kflorence** [spring-cloud/spring-cloud-consul#108]
Perhaps the docs are out of date, but I get the following exception unless I explicitly import `ConsulAutoConfiguration` in conjunction with `@EnableDiscoveryClient` using version `1.0.0.M3`:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'consulRibbonClientConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.cloud.consul.discovery.ConsulDiscoveryProperties org.springframework.cloud.consul.discovery.ConsulRibbonClientConfiguration.properties; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.cloud.consul.discovery.ConsulDiscoveryProperties] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334) ~[spring-beans-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214) ~[spring-beans-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543) ~[spring-beans-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:305) ~[spring-beans-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:301) ~[spring-beans-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:196) ~[spring-beans-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772) ~[spring-beans-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:835) ~[spring-context-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537) ~[spring-context-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.cloud.netflix.ribbon.SpringClientFactory.createContext(SpringClientFactory.java:148) [spring-cloud-netflix-core-1.1.0.M2.jar:1.1.0.M2]
	at org.springframework.cloud.netflix.ribbon.SpringClientFactory.getContext(SpringClientFactory.java:113) [spring-cloud-netflix-core-1.1.0.M2.jar:1.1.0.M2]
	at org.springframework.cloud.netflix.ribbon.SpringClientFactory.getInstance(SpringClientFactory.java:181) [spring-cloud-netflix-core-1.1.0.M2.jar:1.1.0.M2]
	at org.springframework.cloud.netflix.ribbon.SpringClientFactory.getClientConfig(SpringClientFactory.java:98) [spring-cloud-netflix-core-1.1.0.M2.jar:1.1.0.M2]
	at org.springframework.cloud.netflix.feign.ribbon.CachingSpringLoadBalancerFactory.create(CachingSpringLoadBalancerFactory.java:48) [spring-cloud-netflix-core-1.1.0.M2.jar:1.1.0.M2]
	at org.springframework.cloud.netflix.feign.ribbon.LoadBalancerFeignClient.lbClient(LoadBalancerFeignClient.java:72) [spring-cloud-netflix-core-1.1.0.M2.jar:1.1.0.M2]
	at org.springframework.cloud.netflix.feign.ribbon.LoadBalancerFeignClient.execute(LoadBalancerFeignClient.java:52) [spring-cloud-netflix-core-1.1.0.M2.jar:1.1.0.M2]
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:92) [feign-core-8.11.0.jar:8.11.0]
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:71) [feign-core-8.11.0.jar:8.11.0]
	at feign.hystrix.HystrixInvocationHandler$1.run(HystrixInvocationHandler.java:54) [feign-hystrix-8.11.0.jar:8.11.0]
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:294) [hystrix-core-1.4.18.jar:1.4.18]
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:289) [hystrix-core-1.4.18.jar:1.4.18]
	at rx.Observable$2.call(Observable.java:162) [rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) [rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:162) [rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) [rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:162) [rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) [rxjava-1.0.14.jar:1.0.14]
	at rx.Observable.unsafeSubscribe(Observable.java:7710) [rxjava-1.0.14.jar:1.0.14]
	at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:535) [hystrix-core-1.4.18.jar:1.4.18]
	at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:510) [hystrix-core-1.4.18.jar:1.4.18]
	at rx.Observable.unsafeSubscribe(Observable.java:7710) [rxjava-1.0.14.jar:1.0.14]
	at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62) [rxjava-1.0.14.jar:1.0.14]
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56) [hystrix-core-1.4.18.jar:1.4.18]
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47) [hystrix-core-1.4.18.jar:1.4.18]
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69) [hystrix-core-1.4.18.jar:1.4.18]
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) [rxjava-1.0.14.jar:1.0.14]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_40]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_40]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
```

My client is defined as follows:

```scala
@Configuration
@EnableDiscoveryClient
@EnableFeignClients(Array("com.solarmosaic.microservice.utility.client"))
@Import(Array(classOf[ConsulAutoConfiguration]))
class UtilityClientConfiguration
```

**Comment by spencergibb** [comment]
I noticed this today as well, but got around it by using `spring-cloud-starter-consul-all`.
