### ISSUE TITLE
NPE encountered within the spring-cloud-starter-consul-all:1.0.0.BUILD-SNAPSHOT dependency chain

### ISSUE THREAD

**Issue by kabennett** [spring-cloud/spring-cloud-consul#135]
I am encountering a NPE. After debugging the code, it looks like the root cause is in com.netflix.loadbalancer.LoadBalancerContext.reconstructURIWithServer(Server,URI). The host and port are not set on the URI, which later results in a NPE - in com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ClientRequest), the getHost(HttpUriRequest) call fails because the host and port are not set.
 
```
com.netflix.zuul.exception.ZuulException: Forwarding error
	at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.forward(RibbonRoutingFilter.java:135) ~[spring-cloud-netflix-core-1.1.0.BUILD-SNAPSHOT.jar:1.1.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.run(RibbonRoutingFilter.java:76) ~[spring-cloud-netflix-core-1.1.0.BUILD-SNAPSHOT.jar:1.1.0.BUILD-SNAPSHOT]
	at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:112) ~[zuul-core-1.1.0.jar:1.1.0]
	at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:197) ~[zuul-core-1.1.0.jar:1.1.0]
	at com.netflix.zuul.FilterProcessor.runFilters(FilterProcessor.java:161) ~[zuul-core-1.1.0.jar:1.1.0]
	at com.netflix.zuul.FilterProcessor.route(FilterProcessor.java:120) ~[zuul-core-1.1.0.jar:1.1.0]
	at com.netflix.zuul.ZuulRunner.route(ZuulRunner.java:96) ~[zuul-core-1.1.0.jar:1.1.0]
	at com.netflix.zuul.http.ZuulServlet.route(ZuulServlet.java:116) ~[zuul-core-1.1.0.jar:1.1.0]
	at com.netflix.zuul.http.ZuulServlet.service(ZuulServlet.java:81) ~[zuul-core-1.1.0.jar:1.1.0]
	at org.springframework.web.servlet.mvc.ServletWrappingController.handleRequestInternal(ServletWrappingController.java:158) [spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.cloud.netflix.zuul.web.ZuulController.handleRequestInternal(ZuulController.java:43) [spring-cloud-netflix-core-1.1.0.BUILD-SNAPSHOT.jar:1.1.0.BUILD-SNAPSHOT]
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:147) [spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50) [spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959) [spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893) [spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:969) [spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:871) [spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:845) [spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:243) [spring-boot-actuator-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:111) [spring-boot-actuator-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:87) [spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77) [spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121) [spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:103) [spring-boot-actuator-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:521) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1096) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_71]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_71]
Caused by: com.netflix.hystrix.exception.HystrixRuntimeException: authorizationService failed and no fallback available.
	at com.netflix.hystrix.AbstractCommand$16.call(AbstractCommand.java:806) ~[hystrix-core-1.4.23.jar:1.4.23]
	at com.netflix.hystrix.AbstractCommand$16.call(AbstractCommand.java:790) ~[hystrix-core-1.4.23.jar:1.4.23]
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:99) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70) ~[rxjava-1.0.14.jar:1.0.14]
	at com.netflix.hystrix.AbstractCommand$DeprecatedOnFallbackHookApplication$1.onError(AbstractCommand.java:1521) ~[hystrix-core-1.4.23.jar:1.4.23]
	at com.netflix.hystrix.AbstractCommand$FallbackHookApplication$1.onError(AbstractCommand.java:1411) ~[hystrix-core-1.4.23.jar:1.4.23]
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:314) ~[hystrix-core-1.4.23.jar:1.4.23]
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:306) ~[hystrix-core-1.4.23.jar:1.4.23]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable.unsafeSubscribe(Observable.java:7710) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:100) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70) ~[rxjava-1.0.14.jar:1.0.14]
	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$3.onError(AbstractCommand.java:1012) ~[hystrix-core-1.4.23.jar:1.4.23]
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70) ~[rxjava-1.0.14.jar:1.0.14]
	at com.netflix.hystrix.AbstractCommand$DeprecatedOnRunHookApplication$1.onError(AbstractCommand.java:1480) ~[hystrix-core-1.4.23.jar:1.4.23]
	at com.netflix.hystrix.AbstractCommand$ExecutionHookApplication$1.onError(AbstractCommand.java:1376) ~[hystrix-core-1.4.23.jar:1.4.23]
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:297) ~[hystrix-core-1.4.23.jar:1.4.23]
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:289) ~[hystrix-core-1.4.23.jar:1.4.23]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable.unsafeSubscribe(Observable.java:7710) ~[rxjava-1.0.14.jar:1.0.14]
	at com.netflix.hystrix.AbstractCommand$1.call(AbstractCommand.java:384) ~[hystrix-core-1.4.23.jar:1.4.23]
	at com.netflix.hystrix.AbstractCommand$1.call(AbstractCommand.java:363) ~[hystrix-core-1.4.23.jar:1.4.23]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable.unsafeSubscribe(Observable.java:7710) ~[rxjava-1.0.14.jar:1.0.14]
	at com.netflix.hystrix.AbstractCommand$ObservableCommand$1.call(AbstractCommand.java:1140) ~[hystrix-core-1.4.23.jar:1.4.23]
	at com.netflix.hystrix.AbstractCommand$ObservableCommand$1.call(AbstractCommand.java:1136) ~[hystrix-core-1.4.23.jar:1.4.23]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable.subscribe(Observable.java:7804) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable.subscribe(Observable.java:7772) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.internal.operators.BlockingOperatorToFuture.toFuture(BlockingOperatorToFuture.java:57) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.observables.BlockingObservable.toFuture(BlockingObservable.java:400) ~[rxjava-1.0.14.jar:1.0.14]
	at com.netflix.hystrix.HystrixCommand.queue(HystrixCommand.java:379) ~[hystrix-core-1.4.23.jar:1.4.23]
	at com.netflix.hystrix.HystrixCommand.execute(HystrixCommand.java:335) ~[hystrix-core-1.4.23.jar:1.4.23]
	at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.forward(RibbonRoutingFilter.java:119) ~[spring-cloud-netflix-core-1.1.0.BUILD-SNAPSHOT.jar:1.1.0.BUILD-SNAPSHOT]
	... 68 common frames omitted
Caused by: com.netflix.client.ClientException: null
	at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:123) ~[ribbon-loadbalancer-2.1.0.jar:2.1.0]
	at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:81) ~[ribbon-loadbalancer-2.1.0.jar:2.1.0]
	at org.springframework.cloud.netflix.zuul.filters.route.RestClientRibbonCommand.forward(RestClientRibbonCommand.java:135) ~[spring-cloud-netflix-core-1.1.0.BUILD-SNAPSHOT.jar:1.1.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.netflix.zuul.filters.route.RestClientRibbonCommand.run(RestClientRibbonCommand.java:106) ~[spring-cloud-netflix-core-1.1.0.BUILD-SNAPSHOT.jar:1.1.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.netflix.zuul.filters.route.RestClientRibbonCommand.run(RestClientRibbonCommand.java:50) ~[spring-cloud-netflix-core-1.1.0.BUILD-SNAPSHOT.jar:1.1.0.BUILD-SNAPSHOT]
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:294) ~[hystrix-core-1.4.23.jar:1.4.23]
	... 114 common frames omitted
Caused by: java.lang.IllegalArgumentException: Host name may not be null
	at org.apache.http.util.Args.containsNoBlanks(Args.java:81) ~[httpcore-4.4.4.jar:4.4.4]
	at org.apache.http.HttpHost.<init>(HttpHost.java:80) ~[httpcore-4.4.4.jar:4.4.4]
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.getHost(ApacheHttpClient4Handler.java:198) ~[jersey-apache-client4-1.19.jar:1.19]
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:173) ~[jersey-apache-client4-1.19.jar:1.19]
	at com.sun.jersey.api.client.Client.handle(Client.java:652) ~[jersey-client-1.19.jar:1.19]
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682) ~[jersey-client-1.19.jar:1.19]
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74) ~[jersey-client-1.19.jar:1.19]
	at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:570) ~[jersey-client-1.19.jar:1.19]
	at com.netflix.niws.client.http.RestClient.execute(RestClient.java:621) ~[ribbon-httpclient-2.1.0.jar:2.1.0]
	at com.netflix.niws.client.http.RestClient.execute(RestClient.java:527) ~[ribbon-httpclient-2.1.0.jar:2.1.0]
	at com.netflix.niws.client.http.RestClient.execute(RestClient.java:92) ~[ribbon-httpclient-2.1.0.jar:2.1.0]
	at com.netflix.client.AbstractLoadBalancerAwareClient$1.call(AbstractLoadBalancerAwareClient.java:109) ~[ribbon-loadbalancer-2.1.0.jar:2.1.0]
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$3$1.call(LoadBalancerCommand.java:303) ~[ribbon-loadbalancer-2.1.0.jar:2.1.0]
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$3$1.call(LoadBalancerCommand.java:287) ~[ribbon-loadbalancer-2.1.0.jar:2.1.0]
	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:46) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:35) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable.unsafeSubscribe(Observable.java:7710) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.internal.operators.OperatorConcat$ConcatSubscriber.subscribeNext(OperatorConcat.java:176) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.internal.operators.OperatorConcat$ConcatSubscriber.onNext(OperatorConcat.java:140) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.internal.operators.OperatorConcat$ConcatSubscriber.onNext(OperatorConcat.java:79) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55) ~[rxjava-1.0.14.jar:1.0.14]
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:185) ~[ribbon-loadbalancer-2.1.0.jar:2.1.0]
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:180) ~[ribbon-loadbalancer-2.1.0.jar:2.1.0]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable.unsafeSubscribe(Observable.java:7710) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber$1.call(OperatorRetryWithPredicate.java:134) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:80) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:59) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onNext(OperatorRetryWithPredicate.java:86) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onNext(OperatorRetryWithPredicate.java:49) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:46) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:35) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable.subscribe(Observable.java:7804) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.Observable.subscribe(Observable.java:7772) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:432) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.observables.BlockingObservable.single(BlockingObservable.java:331) ~[rxjava-1.0.14.jar:1.0.14]
	at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:102) ~[ribbon-loadbalancer-2.1.0.jar:2.1.0]
	... 119 common frames omitted
```

**Comment by kabennett** [comment]
I switched to Brixton.M5 and still have the same issue.  The org.apache.http.HttpHost(String, int, String) constructor always throws a NPE.  After debugging this, I am trying to figure out how this was ever working for me.  I had to rebuild my environment after the laptop I had been using had to be re-imaged.  I am truly stumped how this code sequence ever worked.

**Comment by kabennett** [comment]
OK, I figured out what my issue was.  The machine naming convention here uses underscores, which, of course, is incompatible with java.net.URI.  When my machine was re-imaged, it was assigned a new name with an underscore in it.  Argh!  Sorry for the confusion folks.
