### ISSUE TITLE
How to disable consul in spring boot application?

### ISSUE THREAD

**Issue by thangavaishnavi** [spring-cloud/spring-cloud-consul#147]

**Comment by thangavaishnavi** [comment]
Getting below execption even after setting spring.cloud.config.enabled:false in yml properties.

com.ecwid.consul.transport.TransportException: java.net.ConnectException: Connection refused: connect
	at com.ecwid.consul.transport.DefaultHttpTransport.executeRequest(DefaultHttpTransport.java:87) ~[consul-api-1.1.6.jar:?]
	at com.ecwid.consul.transport.DefaultHttpTransport.makeGetRequest(DefaultHttpTransport.java:46) ~[consul-api-1.1.6.jar:?]
	at com.ecwid.consul.v1.ConsulRawClient.makeGetRequest(ConsulRawClient.java:66) ~[consul-api-1.1.6.jar:?]
	at com.ecwid.consul.v1.kv.KeyValueConsulClient.getKVValues(KeyValueConsulClient.java:135) ~[consul-api-1.1.6.jar:?]
	at com.ecwid.consul.v1.kv.KeyValueConsulClient.getKVValues(KeyValueConsulClient.java:128) ~[consul-api-1.1.6.jar:?]
	at com.ecwid.consul.v1.ConsulClient.getKVValues(ConsulClient.java:346) ~[consul-api-1.1.6.jar:?]
	at org.springframework.cloud.consul.config.ConsulPropertySource.init(ConsulPropertySource.java:57) ~[spring-cloud-consul-config-1.0.0.M2.jar:1.0.0.M2]
	at org.springframework.cloud.consul.config.ConsulPropertySourceLocator.locate(ConsulPropertySourceLocator.java:70) ~[spring-cloud-consul-config-1.0.0.M2.jar:1.0.0.M2]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:80) ~[spring-cloud-context-1.1.0.M1.jar:1.1.0.M1]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:568) ~[spring-boot-1.2.6.RELEASE.jar:1.2.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304) [spring-boot-1.2.6.RELEASE.jar:1.2.6.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139) [spring-boot-1.2.6.RELEASE.jar:1.2.6.RELEASE]
	at com.hcl.hmtp.security.server.boot.SecurityBootApplication.main(SecurityBootApplication.java:26) [classes/:?]
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.7.0_79]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[?:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339) ~[?:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200) ~[?:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182) ~[?:1.7.0_79]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.7.0_79]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.7.0_79]
	at java.net.Socket.connect(Socket.java:579) ~[?:1.7.0_79]
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:117) ~[httpclient-4.3.6.jar:4.3.6]
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177) ~[httpclient-4.3.6.jar:4.3.6]
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304) ~[httpclient-4.3.6.jar:4.3.6]
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611) ~[httpclient-4.3.6.jar:4.3.6]
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446) ~[httpclient-4.3.6.jar:4.3.6]
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863) ~[httpclient-4.3.6.jar:4.3.6]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72) ~[httpclient-4.3.6.jar:4.3.6]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:214) ~[httpclient-4.3.6.jar:4.3.6]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:160) ~[httpclient-4.3.6.jar:4.3.6]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:136) ~[httpclient-4.3.6.jar:4.3.6]
	at com.ecwid.consul.transport.DefaultHttpTransport.executeRequest(DefaultHttpTransport.java:71) ~[consul-api-1.1.6.jar:?]
	... 12 more
2016-03-02 12:10:02 [Thread-1] INFO  AnnotationConfigApplicationContext:862 - Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@595c9dcd: startup date [Wed Mar 02 12:10:00 IST 2016]; root of context hierarchy
Exception in thread "main" com.ecwid.consul.transport.TransportException: java.net.ConnectException: Connection refused: connect
	at com.ecwid.consul.transport.DefaultHttpTransport.executeRequest(DefaultHttpTransport.java:87)
	at com.ecwid.consul.transport.DefaultHttpTransport.makeGetRequest(DefaultHttpTransport.java:46)
	at com.ecwid.consul.v1.ConsulRawClient.makeGetRequest(ConsulRawClient.java:66)
	at com.ecwid.consul.v1.kv.KeyValueConsulClient.getKVValues(KeyValueConsulClient.java:135)
	at com.ecwid.consul.v1.kv.KeyValueConsulClient.getKVValues(KeyValueConsulClient.java:128)
	at com.ecwid.consul.v1.ConsulClient.getKVValues(ConsulClient.java:346)
	at org.springframework.cloud.consul.config.ConsulPropertySource.init(ConsulPropertySource.java:57)
	at org.springframework.cloud.consul.config.ConsulPropertySourceLocator.locate(ConsulPropertySourceLocator.java:70)
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:80)
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:568)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139)
	at com.hcl.hmtp.security.server.boot.SecurityBootApplication.main(SecurityBootApplication.java:26)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:117)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:214)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:160)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:136)
	at com.ecwid.consul.transport.DefaultHttpTransport.executeRequest(DefaultHttpTransport.java:71)
	... 12 more

**Comment by aatarasoff** [comment]
You should use `spring.cloud.bootstrap.enabled` or 'spring.cloud.consul.enabled' properties.

For local run your application with Gradle you can add configuration as below:
```
bootRun {
    jvmArgs += "-Dspring.cloud.bootstrap.enabled=false"
}
```

**Comment by thangavaishnavi** [comment]
@aatarasoff I tried that as well but nothing is working..

And am using maven not gradle.

**Comment by aatarasoff** [comment]
@thangavaishnavi could you provide here you configuration files or smth else?

**Comment by thangavaishnavi** [comment]
spring.main.show-banner: false
spring.application.name: security-web
spring.cloud.consul.discovery.healthCheckPath: ${management.contextPath}
spring.cloud.consul.discovery.healthCheckInterval: 15s
spring.cloud.consul.discovery.address: ${management.contextPath}

management:
    contextPath: /security-web/poll
    
spring.cloud.bus.enabled: false
spring.cloud.bootstrap.enabled: false
spring.cloud.discovery.enabled: false
spring.cloud.consul.enabled: false
spring.cloud.consul.config.enabled: false
spring.cloud.config.discovery.enabled: false

**Comment by thangavaishnavi** [comment]
tried all false possible, but of no use..

**Comment by spencergibb** [comment]
@thangavaishnavi You need to put it in `bootstrap.yml` because you are using consul config. Why do you need to disable it if you include it as a dependency?

**Comment by thangavaishnavi** [comment]
i want to make deployment disabling consul as well. both should work

**Comment by spencergibb** [comment]
Did you try putting `spring.cloud.consul.enabled: false` in `bootstrap.yml`?

**Comment by thangavaishnavi** [comment]
Yeah, now its working with application.yml as well, I have excluded few dependencies which was creating problem and fixed it. Thank you

**Comment by Sunrry** [comment]
@spencergibb I have a question which is very similar with @thangavaishnavi's.
Here, I find that if I remove the consul dependency from pom.xml, the spring cloud application will not register itself to consul whether there are consul configs  (spring.cloud.consul.enabled: false) in bootstrap.yml or not.  
So why you recommend @thangavaishnavi to add the config (spring.cloud.consul.enabled: false) and not let him to remove the dependency and what is the usage of this config (spring.cloud.consul.enabled: false) ? 
Thank you

**Comment by roman-sinyakov** [comment]
`spring.cloud.consul.config.enabled: false` in `bootstarap.yml` helped me with the same problem

**Comment by raffian** [comment]
Is it possible to enable at runtime if Consul was disabled on startup? We're building a validation agent process to check, among other things, if Consul is up, so the agent starts with Consul disabled but would need to connect to Consul on demand.

**Comment by spencergibb** [comment]
Not automatically.

**Comment by KumareshanS** [comment]
> Did you try putting `spring.cloud.consul.enabled: false` in `bootstrap.yml`?

Thanks. This really saved my day.
