### ISSUE TITLE
Cloud Config does not work for a host different from localhost

### ISSUE THREAD

**Issue by RoadRunner120485** [spring-cloud/spring-cloud-consul#176]
I've created a small playground for testing the features of of spring cloud consul in a docker environment. I'm using a docker container for consul in a bridged network and linking the consul container into my service containers. 
I configured the property `spring.cloud.consul.host` pointing to my consul container:

```
server:
  port: 8080

spring:
  boot:
    admin:
      url: ${admin.server.url}  # should be resolved w/ spring cloud config
      client:
        service-url: http://no-public-domain/${spring.application.name}/
  application:
    name: helloService
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
      host: consul
```
 and getting an Exception on startup:

```
com.ecwid.consul.transport.TransportException: java.net.ConnectException: Connection refused
	at com.ecwid.consul.transport.AbstractHttpTransport.executeRequest(AbstractHttpTransport.java:80)
	at com.ecwid.consul.transport.AbstractHttpTransport.makeGetRequest(AbstractHttpTransport.java:39)
	at com.ecwid.consul.v1.ConsulRawClient.makeGetRequest(ConsulRawClient.java:81)
	at com.ecwid.consul.v1.kv.KeyValueConsulClient.getKVValues(KeyValueConsulClient.java:150)
	at com.ecwid.consul.v1.ConsulClient.getKVValues(ConsulClient.java:399)
	at org.springframework.cloud.consul.config.ConsulPropertySource.init(ConsulPropertySource.java:64)
	at org.springframework.cloud.consul.config.ConsulPropertySourceLocator.create(ConsulPropertySourceLocator.java:134)
	at org.springframework.cloud.consul.config.ConsulPropertySourceLocator.locate(ConsulPropertySourceLocator.java:113)
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:89)
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:640)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:343)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at de.sturmm.app.ServiceApplication.main(ServiceApplication.java:18)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:117)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:882)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:220)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:164)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:139)
	at com.ecwid.consul.transport.AbstractHttpTransport.executeRequest(AbstractHttpTransport.java:64)
	... 12 common frames omitted

23:05:19.821 [main] ERROR o.s.boot.SpringApplication - Application startup failed
com.ecwid.consul.transport.TransportException: java.net.ConnectException: Connection refused
	at com.ecwid.consul.transport.AbstractHttpTransport.executeRequest(AbstractHttpTransport.java:80)
	at com.ecwid.consul.transport.AbstractHttpTransport.makeGetRequest(AbstractHttpTransport.java:39)
	at com.ecwid.consul.v1.ConsulRawClient.makeGetRequest(ConsulRawClient.java:81)
	at com.ecwid.consul.v1.kv.KeyValueConsulClient.getKVValues(KeyValueConsulClient.java:150)
	at com.ecwid.consul.v1.ConsulClient.getKVValues(ConsulClient.java:399)
	at org.springframework.cloud.consul.config.ConsulPropertySource.init(ConsulPropertySource.java:64)
	at org.springframework.cloud.consul.config.ConsulPropertySourceLocator.create(ConsulPropertySourceLocator.java:134)
	at org.springframework.cloud.consul.config.ConsulPropertySourceLocator.locate(ConsulPropertySourceLocator.java:113)
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:89)
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:640)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:343)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at de.sturmm.app.ServiceApplication.main(ServiceApplication.java:18)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:117)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:882)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:220)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:164)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:139)
	at com.ecwid.consul.transport.AbstractHttpTransport.executeRequest(AbstractHttpTransport.java:64)
	... 12 common frames omitted
```

I recognized, that the configured hostname of the consul container will not be not used. The config is ignored and `ConsulClient` still points to `localhost`. IMHO this is a timing problem because the `PropertySourceLocator` is created before the property values of the depending `ConsulProperties` are injected... and as long the properties were not resolved the default values are used. 

When I'm running my services without containers and with consul on localhost then all works fine.

**Comment by RoadRunner120485** [comment]
Arg ... I'll try to move my config to `bootstrap.yml`

**Comment by RoadRunner120485** [comment]
Ok ... that was my fault. Now it works.

**Comment by amitsharma1729** [comment]
What was the fault? I'm having the same issue.

**Comment by spencergibb** [comment]
> move my config to `bootstrap.yml`
