### ISSUE TITLE
HeartbeatProperties intervalValue validation fails

### ISSUE THREAD

**Issue by aantono** [spring-cloud/spring-cloud-consul#184]
When using hibernate-validator-4.2.0.Final library (which automatically gets pulled into the classpath), the validation of https://github.com/spring-cloud/spring-cloud-consul/blob/master/spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/discovery/HeartbeatProperties.java#L48 fails.

The validator that handles the validation is `org.hibernate.validator.constraints.impl.DecimalMinValidatorForNumber`, which has the following implementation of `isValid` method:

```
    public boolean isValid(Number value, ConstraintValidatorContext constraintValidatorContext) {

		//null values are valid
		if ( value == null ) {
			return true;
		}

		if ( value instanceof BigDecimal ) {
			return ( ( BigDecimal ) value ).compareTo( minValue ) != -1;
		}
		else if ( value instanceof BigInteger ) {
			return ( new BigDecimal( ( BigInteger ) value ) ).compareTo( minValue ) != -1;
		}
		else {
			return ( BigDecimal.valueOf( value.longValue() ).compareTo( minValue ) ) != -1;
		}
	}
```

The instance of `Number value` is of type `Double`, so it falls into the `else` block, and tries to compare a `BigDecimal` created from `value.longValue()` which returns `0`, instead of the desired `0.6666666`, thus failing the validation resulting in the following stack trace:
```
Caused by: org.springframework.validation.BindException: org.springframework.boot.bind.RelaxedDataBinder$RelaxedBeanPropertyBindingResult: 1 errors
Field error in object 'spring.cloud.consul.discovery.heartbeat' on field 'intervalRatio': rejected value [0.6666666666666666]; codes [DecimalMin.spring.cloud.consul.discovery.heartbeat.intervalRatio,DecimalMin.intervalRatio,DecimalMin.double,DecimalMin]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [spring.cloud.consul.discovery.heartbeat.intervalRatio,intervalRatio]; arguments []; default message [intervalRatio],0.1]; default message [must be greater than or equal to 0.1]
	at org.springframework.boot.bind.PropertiesConfigurationFactory.validate(PropertiesConfigurationFactory.java:362)
	at org.springframework.boot.bind.PropertiesConfigurationFactory.doBindPropertiesToTarget(PropertiesConfigurationFactory.java:271)
	at org.springframework.boot.bind.PropertiesConfigurationFactory.bindPropertiesToTarget(PropertiesConfigurationFactory.java:241)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:334)
```

**Comment by aantono** [comment]
Looks like this problem goes away after upgrading to hibernate-validator version 4.3.2.Final, as it has the correct implementation of the validation:

```
	public boolean isValid(Number value, ConstraintValidatorContext constraintValidatorContext) {

		//null values are valid
		if ( value == null ) {
			return true;
		}

		if ( value instanceof BigDecimal ) {
			return ( (BigDecimal) value ).compareTo( minValue ) != -1;
		}
		else if ( value instanceof BigInteger ) {
			return ( new BigDecimal( (BigInteger) value ) ).compareTo( minValue ) != -1;
		}
		if ( value instanceof Long ) {
			return ( BigDecimal.valueOf( value.longValue() ).compareTo( minValue ) ) != -1;
		}
		else {
			return ( BigDecimal.valueOf( value.doubleValue() ).compareTo( minValue ) ) != -1;
		}
	}
```

**Comment by spencergibb** [comment]
Unsure why you have such an old version of validator. In boot 1.3.x (what s-c-consul 1.0.x is matched with) has validator 5.2.4
