### ISSUE TITLE
after upgrade to 1.2.0 -> error: Binder NoSuchBeanDefinitionException   

### ISSUE THREAD

**Issue by micjaesc** [spring-cloud/spring-cloud-consul#309]
because I needed configurable Health Indicator (https://github.com/spring-cloud/spring-cloud-consul/issues/244)  , I had to bump version of spring-cloud-starter-consul-all with dependencies to 1.2.0.RELEASE. 

![image](https://cloud.githubusercontent.com/assets/2565178/25952133/0fe6d03c-3660-11e7-8b60-a97a7175f620.png)

After that,  I have bootup problem with below message. Cleaning env, starting from scratch etc doesn't help?
Did I miss some dependency from QuickStart https://cloud.spring.io/spring-cloud-consul/ ?

```
15:36:36.850 [main] DEBUG o.s.b.d.LoggingFailureAnalysisReporter - Application failed to start due to an exception
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.cloud.stream.binder.Binder] is defined
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:348)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:346)
```

**Comment by spencergibb** [comment]
You are mixing version from different release trains. Can you provide your full pom.xml? Also, please don't use screenshots of text.

**Comment by micjaesc** [comment]
I've put `xyz` into company specific part

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <version>3.0-SNAPSHOT</version>
    <groupId>xyz</groupId>
    <artifactId>xyz</artifactId>

    <packaging>jar</packaging>
    <name>xyz</name>
    <description>xyz</description>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.4.1.RELEASE</version>
        <relativePath/>
        <!-- lookup parent from repository -->
    </parent>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>1.8</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
            <version>1.4.1.RELEASE</version>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-tomcat</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-undertow</artifactId>
        </dependency>
        <dependency>
            <groupId>io.reactivex</groupId>
            <artifactId>rxjava</artifactId>
            <version>1.0.13</version>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5</version>
        </dependency>
        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
            <version>1.9</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jersey</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-hystrix</artifactId>
            <version>1.2.0.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-hystrix-dashboard</artifactId>
            <version>1.0.3.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.netflix.archaius</groupId>
            <artifactId>archaius-core</artifactId>
            <version>0.6.0</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>commons-lang</groupId>
            <artifactId>commons-lang</artifactId>
            <version>2.6</version>
        </dependency>
        <dependency>
            <groupId>com.wordnik</groupId>
            <artifactId>swagger-jersey2-jaxrs_2.10</artifactId>
            <version>1.3.12</version>
        </dependency>

        <dependency>
            <groupId>com.github.kristofa</groupId>
            <artifactId>brave-spring-resttemplate-interceptors</artifactId>
            <version>3.0.0-rc-1</version>
        </dependency>

        <dependency>
            <groupId>com.github.kristofa</groupId>
            <artifactId>brave-zipkin-spancollector</artifactId>
            <version>3.0.0-rc-1</version>
        </dependency>

        <dependency>
            <groupId>com.github.kristofa</groupId>
            <artifactId>brave-apache-http-interceptors</artifactId>
            <version>3.0.0-rc-1</version>
        </dependency>

        <dependency>
            <groupId>com.newrelic.agent.java</groupId>
            <artifactId>newrelic-api</artifactId>
            <version>3.21.0</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-consul-all</artifactId>
            <version>1.2.0.RELEASE</version>
            <exclusions>
                <exclusion>
                    <groupId>com.sun.jersey</groupId>
                    <artifactId>jersey-client</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.sun.jersey.contribs</groupId>
                    <artifactId>jersey-apache-client4</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.timgroup</groupId>
            <artifactId>java-statsd-client</artifactId>
            <version>3.1.0</version>
        </dependency>

    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-consul-dependencies</artifactId>
                <version>1.2.0.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Brixton.SR2</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <build>
        <finalName>xyz</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>pl.project13.maven</groupId>
                <artifactId>git-commit-id-plugin</artifactId>
                <version>2.1.10</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>revision</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <prefix>git</prefix>
                    <!-- that's the default value -->
                    <dateFormat>dd.MM.yyyy '@' HH:mm:ss z</dateFormat>
                    <!-- that's the default value -->
                    <verbose>true</verbose>
                    <!-- false is default for this -->
                    <generateGitPropertiesFile>true</generateGitPropertiesFile>
                    <!-- false is default for this -->
                    <dotGitDirectory>${project.basedir}/../.git</dotGitDirectory>
                    <generateGitPropertiesFilename>target/classes/git.properties</generateGitPropertiesFilename>
                    <!-- required, you have to specify this path -->
                </configuration>
            </plugin>
        </plugins>
    </build>

    <repositories>
        <repository>
            <id>spring-snapshots</id>
            <name>Spring Snapshots</name>
            <url>https://repo.spring.io/snapshot</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/milestone</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>java.net</id>
            <url>xyz</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

</project>
```

**Comment by BigMikeATL** [comment]
A encountered this issue last night and spent quite awhile troubleshooting it. 

In my case, the error occurred whenever I set spring.cloud.consul=false in my bootstrap.yml. 

The error is: 
A component required a bean of type 'org.springframework.cloud.stream.binder.Binder' that could not be found. Consider defining a bean of type 'org.springframework.cloud.stream.binder.Binder' in your configuration.

I'm using spring-boot-starter-parent 1.5.3.RELEASE, Dalson.RELEASE, and spring-cloud-starter-consul-all.

If I remove spring-cloud-starter-consul-all and replace it with just spring-cloud-starter-consul-config and spring-cloud-starter-consul-discovery, which are all I really need, then all is well. 

As a side note, I was able to suppress this error by adding spring-cloud-stream-app-starters and a corresponding jdbc component. However, spring ALWAYS tried to connect to consul, even when spring.cloud.config.enabled=false and/or spring.cloud.config.consul.enabled=false.

**Comment by spencergibb** [comment]
@micjaesc you are trying to combine version from release trains. That is not supported. consul 1.2.0.RELEASE is from the Dalston release train.

@BigMikeATL you have spring-cloud-stream on the classpath, but no binder (you disabled consul). If you don't want consul bus, don't use the consul-all starter.

**Comment by BigMikeATL** [comment]
@spencergibb That's what I figured after yesterday's lengthy debugging session. :) This caught me off guard since I had used consul-all in past projects without incident -- others might be making the same mistake as 'bus' is a new component as of 1.2.0.RELEASE

However, I feel like disabling consul shouldn't stop my app from running simply because the stream library is present.

**Comment by spencergibb** [comment]
Actually, it's since 1.1.0.RELEASE

**Comment by spencergibb** [comment]
> because the stream library is present

That's the behaviour of the stream library. @mbogoevici thoughts?

**Comment by BigMikeATL** [comment]
As an FYI - When I added dependencies that were sufficient to get stream to stop complaining, my app would still try to connect to consul even though consul.enabled was set to false in bootstrap.yml

**Comment by ulisses79** [comment]
Hi,
I use this flag in yml file:
`management.health.consul.enabled: false`
but healt endpoint still reports consul as one of my healthchecks:
`discoveryComposite": {
"description": "Spring Cloud Consul Discovery Client",
"status": "UP",
"discoveryClient": {
"description": "Spring Cloud Consul Discovery Client",
"status": "UP",
"services": [
"consul",
....
"consul": {
"status": "UP",
"services": {
"consul": [],`

**Comment by obfischer** [comment]
I suffer from the same problem and would be interessted in solution.

**Comment by spencergibb** [comment]
@obfischer don't use the `-all` starter if you don't want to use consul's bus

**Comment by spencergibb** [comment]
Use the separate starters

**Comment by yvladimirov** [comment]
you can add `spring.cloud.bus.enabled=false` with `spring.cloud.consul.enabled=false`

**Comment by puppylpg** [comment]
> @micjaesc you are trying to combine version from release trains. That is not supported. consul 1.2.0.RELEASE is from the Dalston release train.
> 
> @BigMikeATL you have spring-cloud-stream on the classpath, but no binder (you disabled consul). If you don't want consul bus, don't use the consul-all starter.

Thanks, I use `spring-cloud-start-consul-all` and wanna disable consul when testing, then the same error about binder arose. I haved changed it to `spring-cloud-start-consul-discovery` and it works! Thanks a lot.
