### ISSUE TITLE
Config failFast not respected by consul-binder EventService

### ISSUE THREAD

**Issue by stefanroeck** [spring-cloud/spring-cloud-consul#328]
Per documentation the purpose of spring.cloud.consul.config,failFast is to not fail once consul isn't available for configuration.

Steps:
- In Boostrap.yml set spring.cloud.consul.config,failFast=false
- Let consul host point to an invalid host name or port
- Startup Spring Boot application with @EnableDiscoveryClient

Expected:
- Application running, showing warnings in the log that consul is not available

Actual:
- Application doesn't start, exception:

```
16:40:35.118 [main] ERROR o.s.boot.SpringApplication - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'eventService': Invocation of init method failed; nested exception is com.ecwid.consul.transport.TransportException: org.apache.http.conn.HttpHostConnectException: Connect to consul:8501 [consul/127.0.0.1] failed: Connection refused: connect
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:137)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.getBinderInstance(DefaultBinderFactory.java:208)
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.getBinder(DefaultBinderFactory.java:151)
	at org.springframework.cloud.stream.binding.BindingService.getBinder(BindingService.java:155)
	at org.springframework.cloud.stream.binding.BindingService.bindProducer(BindingService.java:111)
	at org.springframework.cloud.stream.binding.BindableProxyFactory.bindOutputs(BindableProxyFactory.java:238)
	at org.springframework.cloud.stream.binding.OutputBindingLifecycle.start(OutputBindingLifecycle.java:57)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:175)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:50)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:348)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:151)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:114)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:879)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151)
```

**Comment by spencergibb** [comment]
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

**Comment by spencergibb** [comment]
`spring.cloud.consul.config.fail-fast` is specifically for loading configuration from consul, not the binder, so it is not expected to work.

**Comment by spencergibb** [comment]
This is a behaviour of spring cloud stream. I believe there may be an issue to support something like this. @garyrussell or @viniciusccarvalho does this ring a bell (not failing hard if the binder isn't available at startup)?

**Comment by garyrussell** [comment]
Spring Cloud Stream is trying to create a separate application context for the `ConsulBinder`, which is failing to create the `EventService`.

Stream itself is not aware of consul; I am not sure how easy it will be to make stream capable of lazy-loading binders, or whether it would be easier to make the `ConsulBinder` able to lazy load the `EventService`. 

cc/ @mbogoevici

**Comment by viniciusccarvalho** [comment]
@garyrussell I think the latter would make more sense, I'm not sure we can make lazy loading of binders today due requirements on provisioning. It's something we can discuss as improvements for 2.0 perhaps.

**Comment by mbogoevici** [comment]
@garyrussell @viniciusccarvalho At a first glance this looks similar to what we do for Rabbit MQ - the binding process completes, but the consuming/producing endpoints are waiting until the broker is available.

**Comment by garyrussell** [comment]
?? 

    16:40:35.118 [main] ERROR o.s.boot.SpringApplication - Application startup failed
    ...
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.getBinderInstance(DefaultBinderFactory.java:208)


It looks to me like  bootstrapping the binder fails; it's well before we create any endpoints.

**Comment by mbogoevici** [comment]
@garyrussell I meant that the solution to this should be similar to what we do for Rabbit MQ. I'm not aware why exactly this fails for Consul but I guess there is an expectation that the application context is started correctly even when the connection is not available. Cf. https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/12 - you think this is this different in nature ?

**Comment by Nexucis** [comment]
Hi,

I have the same problem. The issue is still open, does it mean that no solutions have been found yet ?

In that case, do I have to use the [official library](https://github.com/OrbitzWorldwide/consul-client) directly or [ecwid/consul-api](https://github.com/Ecwid/consul-api) ?

**Comment by spencergibb** [comment]
The binder can be disabled via `spring.cloud.consul.binder.enabled=false`.

**Comment by achaturvedi81** [comment]
@spencergibb I am facing the same issue after upgrading to the latest version of spring cloud with spring boot upgrade. I tried 
spring.cloud.consul.binder.enabled=false.

its giving another error

`org.springframework.context.ApplicationContextException: Failed to start bean 'outputBindingLifecycle'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.cloud.stream.binder.Binder<?, ?, ?>' available
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:185)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:879)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:163)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at com.art.service.promotion.Application.main(Application.java:10)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.cloud.stream.binder.Binder<?, ?, ?>' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:343)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:335)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1101)
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.getBinderInstance(DefaultBinderFactory.java:252)
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.doGetBinder(DefaultBinderFactory.java:174)
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.getBinder(DefaultBinderFactory.java:120)
	at org.springframework.cloud.stream.binding.BindingService.getBinder(BindingService.java:313)
	at org.springframework.cloud.stream.binding.BindingService.bindProducer(BindingService.java:214)
	at org.springframework.cloud.stream.binding.BindableProxyFactory.createAndBindOutputs(BindableProxyFactory.java:262)
	at org.springframework.cloud.stream.binding.OutputBindingLifecycle.doStartWithBindable(OutputBindingLifecycle.java:55)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:47)
	at org.springframework.cloud.stream.binding.OutputBindingLifecycle.start(OutputBindingLifecycle.java:34)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182)`

**Comment by achaturvedi81** [comment]
Noticed if i am changing following property application is coming up fine
`spring:
   cloud:
      bus:
         enabled: false`
