### ISSUE TITLE
Need example for config using token with custom path separator

### ISSUE THREAD

**Issue by raffian** [spring-cloud/spring-cloud-consul#379]
Java 1.8
SPCC - 1.3.0-RELEASE

I've stored a simple value in Consul: `servicename`

```
> consul kv get  -token=*******  -http-addr=http://myconsul:8500 config/helloworldclient/dev
> {"servicename":"gotmilk"}
```

```
spring:
  application:
    name: helloworldclient
  cloud:
    discovery:
      register: false
      enabled: false
    consul:
      prefix: config
      defaultContext: helloworldclient
      profileSeparator: '/'
      token: ******
      host: http://myconsul
      port: 8500
      config:
        enabled: true
      discovery:
        enabled: false
```

```
@RefreshScope
@Configuration
public class AppProperties {
    public String getServicename() {
        return servicename;
    }
    public void setServicename(String servicename) {
        this.servicename = servicename;
    }
    @Value("${servicename}")
    private String servicename;
```

**Keep getting this error on startup:**
```
> java -jar -Dspring.profiles.active=dev target\consul_test-1.0.jar
SLF4J: The requested version 1.7.16 by your slf4j binding is not compatible with [1.6]
SLF4J: See http://www.slf4j.org/codes.html#version_mismatch for further details.
2017-12-12 16:02:02.339  INFO 3320 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@68fb2c38: startup date [Tue Dec 12 16:02:02 EST 2017]; root of context hierarchy
2017-12-12 16:02:02.691  INFO 3320 --- [           main] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2017-12-12 16:02:02.751  INFO 3320 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'configurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$19a7b3db] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \ ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /  =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.8.RELEASE)

2017-12-12 16:02:04.254  INFO 3320 --- [           main] b.c.PropertySourceBootstrapConfiguration : Located property source: CompositePropertySource [name='consul', propertySources=[ConsulPropertySource@254749889 {name='config/helloworldclient,dev/', properties=com.ecwid.consul.v1.ConsulClient@3a079870}, ConsulPropertySource@992802731 {name='config/helloworldclient/', properties=com.ecwid.consul.v1.ConsulClient@3a079870}, ConsulPropertySource@715521683 {name='config/application,dev/', properties=com.ecwid.consul.v1.ConsulClient@3a079870}, ConsulPropertySource@1545242146 {name='config/application/', properties=com.ecwid.consul.v1.ConsulClient@3a079870}]]
2017-12-12 16:02:04.280  INFO 3320 --- [           main] com.ofi.devops.App                       : The following profiles are active: dev
2017-12-12 16:02:04.309  INFO 3320 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@3d299e3: startup date [Tue Dec 12 16:02:04 EST 2017]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@68fb2c38
2017-12-12 16:02:05.155  INFO 3320 --- [           main] o.s.i.config.IntegrationRegistrar        : No bean named 'integrationHeaderChannelRegistry' has been explicitly defined. Therefore, a default DefaultHeaderChannelRegistry will be created.
2017-12-12 16:02:05.563  INFO 3320 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=8b5df4ea-a844-3722-a584-24a2fe745bf7
2017-12-12 16:02:05.574  INFO 3320 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'errorChannel' has been explicitly defined. Therefore, a default PublishSubscribeChannel will be created.
2017-12-12 16:02:05.577  INFO 3320 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'taskScheduler' has been explicitly defined. Therefore, a default ThreadPoolTaskScheduler will be created.
2017-12-12 16:02:05.588  INFO 3320 --- [           main] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2017-12-12 16:02:05.723  INFO 3320 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.netflix.metrics.MetricsInterceptorConfiguration$MetricsRestTemplateConfiguration' of type [org.springframework.cloud.netflix.metrics.MetricsInterceptorConfiguration$MetricsRestTemplateConfiguration$$EnhancerBySpringCGLIB$$2fba571f] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-12-12 16:02:05.806  INFO 3320 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'integrationGlobalProperties' of type [org.springframework.beans.factory.config.PropertiesFactoryBean] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-12-12 16:02:05.807  INFO 3320 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'integrationGlobalProperties' of type [java.util.Properties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-12-12 16:02:05.840  INFO 3320 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$19a7b3db] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-12-12 16:02:05.878  INFO 3320 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.stream.config.BindingServiceConfiguration$PostProcessorConfiguration' of type [org.springframework.cloud.stream.config.BindingServiceConfiguration$PostProcessorConfiguration$$EnhancerBySpringCGLIB$$bf554ee3] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-12-12 16:02:05.905  INFO 3320 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.stream.config.SpelExpressionConverterConfiguration' of type [org.springframework.cloud.stream.config.SpelExpressionConverterConfiguration$$EnhancerBySpringCGLIB$$fdca08d3] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-12-12 16:02:05.914  INFO 3320 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'spelConverter' of type [org.springframework.cloud.stream.config.SpelExpressionConverterConfiguration$SpelConverter] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-12-12 16:02:05.918  INFO 3320 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'spring.cloud.stream.integration-org.springframework.cloud.stream.config.SpringIntegrationProperties' of type [org.springframework.cloud.stream.config.SpringIntegrationProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-12-12 16:02:06.354  INFO 3320 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 8080 (http)
2017-12-12 16:02:06.368  INFO 3320 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2017-12-12 16:02:06.372  INFO 3320 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.23
2017-12-12 16:02:06.497  INFO 3320 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2017-12-12 16:02:06.498  INFO 3320 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 2189 ms
2017-12-12 16:02:06.812  INFO 3320 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Mapping servlet: 'dispatcherServlet' to [/]
2017-12-12 16:02:06.816  INFO 3320 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'metricsFilter' to: [/*]
2017-12-12 16:02:06.817  INFO 3320 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2017-12-12 16:02:06.817  INFO 3320 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2017-12-12 16:02:06.817  INFO 3320 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2017-12-12 16:02:06.817  INFO 3320 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]

2017-12-12 16:02:06.817  INFO 3320 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'webRequestLoggingFilter' to: [/*]
2017-12-12 16:02:06.817  INFO 3320 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'applicationContextIdFilter' to: [/*]
2017-12-12 16:02:06.917  WARN 3320 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'app': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'servicename' in value "${servicename}"
2017-12-12 16:02:06.918  INFO 3320 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2017-12-12 16:02:06.938  INFO 3320 --- [           main] utoConfigurationReportLoggingInitializer :

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2017-12-12 16:02:06.950 ERROR 3320 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'app': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'servicename' in value "${servicename}"
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:372) ~[spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264) ~[spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553) ~[spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) ~[spring-context-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplica
```

**Comment by raffian** [comment]
Why does the property source not reflect the custom path separator '/'? Appears to still use ','

```
2017-12-12 16:02:04.254  INFO 3320 --- [           main] b.c.PropertySourceBootstrapConfiguration : Located property source: CompositePropertySource [name='consul', propertySources=[ConsulPropertySource@254749889 {name='config/helloworldclient,dev/', properties=com.ecwid.consul.v1.ConsulClient@3a079870}, ConsulPropertySource@992802731 {name='config/helloworldclient/', properties=com.ecwid.consul.v1.ConsulClient@3a079870}, ConsulPropertySource@715521683 {name='config/application,dev/', properties=com.ecwid.consul.v1.ConsulClient@3a079870}, ConsulPropertySource@1545242146 {name='config/application/', properties=com.ecwid.consul.v1.ConsulClient@3a079870}]]
```

**Comment by spencergibb** [comment]
Is your configuration in bootstrap.yml?

**Comment by raffian** [comment]
@spencergibb Yes, the config above is boostrap.yml, we also have `application-(dev|qa|prod).properties` containing some package-level logging config, I don't believe that's the problem but I'll remove those files to see if it has any impact.

**Comment by raffian** [comment]
Found a discrepancy I thought was worth mentioning, when editing bootstrap.yml using InfelliJ, code completion suggests `path-separator` and `acl-token` as keys, but  SCC 1.3 source code appears to use `pathSeparator` and `token` . Tested both but found no difference in error message. Does SCC raise security exception if client provides wrong token or no token when one is required?

**Comment by raffian** [comment]
I think we found the issue, still can't read the value, likely reason is how we're storing K/V in Consul>
This is how the app sees Consul config, as reported from the Springboot Consul endpoint "8080/consul"...

```
{
   profiles: [
      "dev"
   ],
   server.ports: {
      local.server.port: 8080
   },
   consul:config/helloworldclient/dev/: {

   },
   consul:config/helloworldclient/: {
      dev: "{"servicename":"dev_env"}",
      qa: "{"servicename":"qa_env"}",
   },
   consul:config/application/dev/: { },
   consul:config/application/: { }
   }
}
```

Since we're using spring profiles, the root config is at `config/helloworldclient/dev/`, (for dev profile), but as depicted above that key contains no data. Not sure if we can read from the other roots, tried using `ConfigurationProperties("dev")` but that did not work. Probably better to fix this in the source than to hack it in the client.

**Comment by raffian** [comment]
Key structure issue, resolve in Consul.

**Comment by jaspreetcj** [comment]
HI @raffian ,

Can you please help with the resolution, I am facing the exact issue, my spring boot application is not able to read consul properties, hence error java.lang.IllegalArgumentException: Could not resolve placeholder

**Comment by raffian** [comment]
You're having trouble reading Consul config properties such that the app fails to startup, or the app starts up but can't read application arbitrary config keys in the Consul registry? Please provide some example of what you're trying to read and the accompanying code.

If the issue is unable to read Consul standard config property like hostname, zone, etc., find the source code for the Consul Cloud library you're using and make sure that property is valid. You may be accessing a config property that was either deprecated and removed or not available because you're using an earlier version of the library.

Hope it helps,
Raffi
