### ISSUE TITLE
OperationException - 'Internal Server Error', rpc error: No cluster leader

### ISSUE THREAD

**Issue by siddharthchopra84** [spring-cloud/spring-cloud-consul#386]
We are using Spring Cloud (Consul) for service discovery and the consul agent service (3 Node deployment) is deployed with other application service (10 Micro Services) on a AWS Stack.

Recently, we have started noticing intermittent RPC Error, which leads to Re-election of leader and following ERROR is raised from Spring Cloud library, and on monitoring we notice that the service discovery is working as expected and new leader is immeditely elected.

So basically, this ERROR is causing noise in our system.

We were thinking on following lines -

1. Is there a way to only raise this ERROR if the cluster leader is not found by enabling some retry mechanism based on number of tries/ duration ?
2. Any other ERROR which spring consul library would generate if the consul leader is actually not available ? so that we can suppress this ERROR/ raise it as a WARN.

Please suggest.
```
ERROR ip-XX-XX-XX-XXX | [pool-3-thread-1] org.springframework.cloud.consul.discovery.ConsulCatalogWatch         Error watching Consu
l CatalogServices
"com.ecwid.consul.v1.OperationException: OperationException(statusCode=500, statusMessage='Internal Server Error', statusContent='rpc error: rpc error: No cl
uster leader')
        at com.ecwid.consul.v1.catalog.CatalogConsulClient.getCatalogServices(CatalogConsulClient.java:122)
        at com.ecwid.consul.v1.catalog.CatalogConsulClient.getCatalogServices(CatalogConsulClient.java:108)
        at com.ecwid.consul.v1.ConsulClient.getCatalogServices(ConsulClient.java:320)
        at org.springframework.cloud.consul.discovery.ConsulCatalogWatch.catalogServicesWatch(ConsulCatalogWatch.java:65)
        at sun.reflect.GeneratedMethodAccessor121.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by spencergibb** [comment]
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

>  consul agent service (3 Node deployment)

This seems odd to me. Do you mean you have a 3 node consul **server** deployment? Are you pointing spring cloud consul at local agents or at the servers?

**Comment by siddharthchopra84** [comment]
Deployment Architecture -
1. **Server**: 3 Node Consul Server Deployment
2. **Agent**: Every application service has it own local agent.

**Comment by siddharthchopra84** [comment]
Deployment Architecture -

Server: 3 Node Consul Server Deployment
Agent: Every application service has it own local agent.

**Comment by spencergibb** [comment]
I won't change it from `ERROR` to `WARN` as an operation is actually failing. That error is coming from the agent. It's in a scheduled method, does it go away?

**Comment by siddharthchopra84** [comment]
Yes, the error goes away as the new leader is elected, but every service on the VPC throws an instance of this exception. So, we see lot of failures during the leader re-election process and then everything is back to normal.

**Comment by spencergibb** [comment]
I don't know what to say. It's a real error. You're welcome to turn that logger off.

**Comment by siddharthchopra84** [comment]
Is there a way find out if re-election of leader failed ? If that is available then we can suppress this ERROR and look out for error when leader re-elections is failed.

**Comment by spencergibb** [comment]
Couldn't it be a legitimate error that someone else wouldn't want to ignore? I don't see what I can do on this side.

**Comment by spencergibb** [comment]
@gamefundas it's our recommendation to not point consul clients at the server cluster but at a local agent. There is an open issue to reregister if the agent restarts.
