### ISSUE TITLE
Java 9 incompatibility

### ISSUE THREAD

**Issue by lazystone** [spring-cloud/spring-cloud-consul#390]
Seems like ecwid.consul-api used by spring-cloud-consul is not java 9 compatible:
```
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at com.ecwid.consul.v1.kv.model.GetValue.getDecodedValue(GetValue.java:99) ~[consul-api-1.3.0.jar!/:?]
	at com.ecwid.consul.v1.kv.model.GetValue.getDecodedValue(GetValue.java:103) ~[consul-api-1.3.0.jar!/:?]
	at org.springframework.cloud.consul.config.ConsulPropertySource.parsePropertiesInKeyValueFormat(ConsulPropertySource.java:102) ~[spring-cloud-consul-config-2.0.0.M4.jar!/:2.0.0.M4]
	at org.springframework.cloud.consul.config.ConsulPropertySource.init(ConsulPropertySource.java:75) ~[spring-cloud-consul-config-2.0.0.M4.jar!/:2.0.0.M4]
	at org.springframework.cloud.consul.config.ConsulPropertySourceLocator.create(ConsulPropertySourceLocator.java:155) ~[spring-cloud-consul-config-2.0.0.M4.jar!/:2.0.0.M4]
	at org.springframework.cloud.consul.config.ConsulPropertySourceLocator.locate(ConsulPropertySourceLocator.java:129) ~[spring-cloud-consul-config-2.0.0.M4.jar!/:2.0.0.M4]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:94) ~[spring-cloud-context-2.0.0.M5.jar!/:2.0.0.M5]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:626) ~[spring-boot-2.0.0.RC1.jar!/:2.0.0.RC1]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:366) ~[spring-boot-2.0.0.RC1.jar!/:2.0.0.RC1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:325) ~[spring-boot-2.0.0.RC1.jar!/:2.0.0.RC1]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:136) ~[spring-boot-2.0.0.RC1.jar!/:2.0.0.RC1]
	at com.cabonline.order.Runner.main(Runner.java:15) ~[classes!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[order-service-622.jar:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[order-service-622.jar:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) ~[order-service-622.jar:?]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) ~[order-service-622.jar:?]
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
```

Related issue: Ecwid/consul-api/issues/143

**Comment by spencergibb** [comment]
Closing in favor of https://github.com/Ecwid/consul-api/issues/143

**Comment by lazystone** [comment]
@spencergibb are you sure that you want just to close the issue? Is it solved?
What if won't be solved in the consul-api for some reasons?

**Comment by spencergibb** [comment]
`--add-modules java.xml.bind` is the workaround. Not using `javax.xml.bind.DatatypeConverter` is something that can only be fixed on their side. Nothing we can do.

**Comment by lazystone** [comment]
I think in the worst case you can fork consul-api, or migrate to another api client or implementing your own. I believe there are many things which you or community can do in that case.
If problem is solved in the consul-api project, then this issue can be used as a signal to bump up the consul-api version at least.
spring-cloud-consul is a satellite of spring boot, where version 2.0 claims to be Java 9 compatible. Therefore this project also must aim for Java 9 compatibility, so I think closing it is just wrong - there is a problem and it has to be addressed.

**Comment by spencergibb** [comment]
Not going to fork. https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-with-Java-9

**Comment by spencergibb** [comment]
I watch `consul-api` so I know when it is released.

**Comment by spencergibb** [comment]
In the meantime, there is a workaround.

**Comment by lazystone** [comment]
@spencergibb time to reopen this one?
