### ISSUE TITLE
Support for reactive Spring (Webflux)

### ISSUE THREAD

**Issue by Wintereise** [spring-cloud/spring-cloud-consul#408]
Hi,

Attempting to add this to a project built on Spring Webflux (2.0.1.BUILD-SNAPSHOT currently).

However, it appears that `spring-cloud-consul-core` has a dependency on the older Spring-web API. 

Pulling it in seems to break WebFlux init (by initiating duplicate beans, which is standard if web gets added to a webflux project).

Am I doing something wrong, or is webflux currently not supported?

```
buildscript {
	ext {
		springBootVersion = '2.0.1.BUILD-SNAPSHOT'
	}
	repositories {
		jcenter()
		mavenCentral()
		maven { url "https://repo.spring.io/snapshot" }
		maven { url "https://repo.spring.io/milestone" }
		maven { url 'https://repo.spring.io/plugins-release' }
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
		classpath 'io.spring.gradle:propdeps-plugin:0.0.9.RELEASE'
		classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.7.3'
	}
}

apply plugin: 'idea'
apply plugin: 'java'
apply plugin: 'maven-publish'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'
apply plugin: 'propdeps'
apply plugin: 'propdeps-idea'
apply plugin: 'com.jfrog.bintray'

group = 'net.azuretemple'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = 1.9

repositories {
	jcenter()
	mavenCentral()
	maven { url "https://repo.spring.io/snapshot" }
	maven { url "https://repo.spring.io/milestone" }
}

configurations {
	compile.exclude module: 'spring-boot-starter-reactor-netty'
	compile.exclude module: 'spring-boot-starter-logging'
	compile.exclude module: 'spring-boot-starter-web'
	compile.exclude group: 'ch.qos.logback'
}

task wrapper(type: Wrapper) {
	gradleVersion = '4.6.0'
}

bootJar {
	launchScript()
}

dependencies {
	compile(
			// Spring (core) libraies
			'org.springframework.boot:spring-boot-starter-actuator',
			'org.springframework.boot:spring-boot-starter-cache',
			'org.springframework.boot:spring-boot-starter-webflux',
			'org.springframework.boot:spring-boot-starter-log4j2',
			'org.springframework.boot:spring-boot-starter-undertow',
			'org.springframework.boot:spring-boot-starter-security',

			// Non-core spring libraries, their versions do NOT scale with the boot release
			'org.springframework.cloud:spring-cloud-starter-consul-discovery:2.0.0.M7',
			'org.springframework.cloud:spring-cloud-starter-consul-config:2.0.0.M7',

			// Generic libraries
			// JWT
			'io.jsonwebtoken:jjwt:0.9.0',
			// Disruptor (for Log4j2 async)
			'com.lmax:disruptor:3.3.7',
			// Caching
			'com.hazelcast:hazelcast-spring:3.9.2',
			'com.github.ben-manes.caffeine:caffeine',
			// Serialization (JSON)
			'com.fasterxml.jackson.module:jackson-module-afterburner:2.9.3',
			// DAO
			'com.arangodb:arangodb-spring-data:2.0.2',
			// Password Strength Checking
			'com.nulab-inc:zxcvbn:1.2.3',
			// Search
			//'org.elasticsearch:elasticsearch:6.2.2',
			//'org.elasticsearch.client:transport:6.2.2',
			//'org.elasticsearch.plugin:transport-netty4-client:6.2.2',

			// Language Utilities
			'org.apache.commons:commons-lang3:3.7'
	)
	optional "org.springframework.boot:spring-boot-configuration-processor"
	compileOnly('org.projectlombok:lombok:1.16.20')
	testCompile(
			'org.springframework.boot:spring-boot-starter-test',
			'io.projectreactor:reactor-test',
			'org.springframework.security:spring-security-test'
	)
}


compileJava.dependsOn(processResources)
```

Error is standard (is what happens when two contexts try loading):

```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userRepository': Unsatisfied dependency expressed through constructor parameter 1: Ambiguous argument values for parameter
 of type [com.arangodb.springframework.core.ArangoOperations] - did you specify the correct bean references as arguments?
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:716) ~[spring-beans-5.0.5.BUILD-SNAPSHOT.jar:5.0.5.BUILD-SNAPSHOT]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:192) ~[spring-beans-5.0.5.BUILD-SNAPSHOT.jar:5.0.5.BUILD-SNAPSHOT]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1270) ~[spring-beans-5.0.5.BUILD-SNAPSHOT.jar:5.0.5.BUILD-SNAPSHOT]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1127) ~[spring-beans-5.0.5.BUILD-SNAPSHOT.jar:5.0.5.BUILD-SNAPSHOT]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getSingletonFactoryBeanForTypeCheck(AbstractAutowireCapableBeanFactory.java:946) ~[spring-beans-5.0.5.BUILD-SNAPSHOT.jar:5.0.5.BUIL
D-SNAPSHOT]
```

**Comment by spencergibb** [comment]
spring-cloud-consul-core has an optional dependency on spring-boot-starter-web. Your error above doesn't seem to have anything to do with consul

**Comment by Wintereise** [comment]
Hi spencer,

I think I was missing the bom, actually.

i.e:

```

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}
```

I added this and it started working, sorry for wasting your time.
