### ISSUE TITLE
Consul Retry is not working

### ISSUE THREAD

**Issue by nazar-mykolyshyn** [spring-cloud/spring-cloud-consul#419]
Consul Retry configuration is not working.
Versions used:
Spring Boot - 2.0.1.RELEASE
Spring Cloud - Finchley.RC1
`spring-retry` and `spring-boot-starter-aop`  are added to the classpath. 

When Consul is not available application fails with `java.net.ConnectException` without retrying. I created sample demo application:
https://github.com/nazar-mykolyshyn/consul-retry-demo

Some personal/team Investigation results (hope may be helpful):
`consulRetryInterceptor`  bean is created, but method that is marked as `@Retryable` is called from 
`AbstractAutoServiceRegistration` in such way: 
```
this.start(); 
```
And probably this is the reason why aop is not intercepting this call.
```
......
public class ConsulAutoServiceRegistration 
       extends AbstractAutoServiceRegistration<ConsulRegistration> {
......
@Override
@Retryable(interceptor = "consulRetryInterceptor")
public void start() {
	super.start();
}
......
///////

public abstract class AbstractAutoServiceRegistration<R extends Registration>
		implements AutoServiceRegistration, ApplicationContextAware {
......
@EventListener(WebServerInitializedEvent.class)
public void bind(WebServerInitializedEvent event) {
	......
        this.start();
}
......
```

Error logs:

```
2018-05-08 13:02:29.992  INFO 5699 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2018-05-08 13:02:30.004  INFO 5699 --- [           main] o.s.c.c.s.ConsulServiceRegistry          : Registering service with consul: NewService{id='consul-retry-demo', name='consul-retry-demo', tags=[secure=false], address='172.23.15.20', port=8080, enableTagOverride=null, check=Check{script='null', interval='10s', ttl='null', http='http://172.23.15.20:8080/actuator/health', tcp='null', timeout='null', deregisterCriticalServiceAfter='null', tlsSkipVerify=null, status='null'}, checks=null}
2018-05-08 13:02:30.049 ERROR 5699 --- [           main] o.s.c.c.s.ConsulServiceRegistry          : Error registering service with consul: NewService{id='consul-retry-demo', name='consul-retry-demo', tags=[secure=false], address='172.23.15.20', port=8080, enableTagOverride=null, check=Check{script='null', interval='10s', ttl='null', http='http://172.23.15.20:8080/actuator/health', tcp='null', timeout='null', deregisterCriticalServiceAfter='null', tlsSkipVerify=null, status='null'}, checks=null}

com.ecwid.consul.transport.TransportException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8500 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
	at com.ecwid.consul.transport.AbstractHttpTransport.executeRequest(AbstractHttpTransport.java:77) ~[consul-api-1.3.1.jar:na]
	at com.ecwid.consul.transport.AbstractHttpTransport.makePutRequest(AbstractHttpTransport.java:41) ~[consul-api-1.3.1.jar:na]
	at com.ecwid.consul.v1.ConsulRawClient.makePutRequest(ConsulRawClient.java:135) ~[consul-api-1.3.1.jar:na]
	at com.ecwid.consul.v1.agent.AgentConsulClient.agentServiceRegister(AgentConsulClient.java:273) ~[consul-api-1.3.1.jar:na]
	at com.ecwid.consul.v1.ConsulClient.agentServiceRegister(ConsulClient.java:309) ~[consul-api-1.3.1.jar:na]
	at org.springframework.cloud.consul.serviceregistry.ConsulServiceRegistry.register(ConsulServiceRegistry.java:64) [spring-cloud-consul-discovery-2.0.0.RC1.jar:2.0.0.RC1]
	at org.springframework.cloud.consul.serviceregistry.ConsulServiceRegistry.register(ConsulServiceRegistry.java:41) [spring-cloud-consul-discovery-2.0.0.RC1.jar:2.0.0.RC1]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.register(AbstractAutoServiceRegistration.java:209) [spring-cloud-commons-2.0.0.RC1.jar:2.0.0.RC1]
	at org.springframework.cloud.consul.serviceregistry.ConsulAutoServiceRegistration.register(ConsulAutoServiceRegistration.java:78) [spring-cloud-consul-discovery-2.0.0.RC1.jar:2.0.0.RC1]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.start(AbstractAutoServiceRegistration.java:108) [spring-cloud-commons-2.0.0.RC1.jar:2.0.0.RC1]
	at org.springframework.cloud.consul.serviceregistry.ConsulAutoServiceRegistration.start(ConsulAutoServiceRegistration.java:68) [spring-cloud-consul-discovery-2.0.0.RC1.jar:2.0.0.RC1]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.bind(AbstractAutoServiceRegistration.java:73) [spring-cloud-commons-2.0.0.RC1.jar:2.0.0.RC1]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration$$FastClassBySpringCGLIB$$e099d3fe.invoke(<generated>) [spring-cloud-commons-2.0.0.RC1.jar:2.0.0.RC1]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:747) [spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) [spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke(AnnotationAwareRetryOperationsInterceptor.java:156) [spring-retry-1.2.2.RELEASE.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) [spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) [spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.cloud.consul.serviceregistry.ConsulAutoServiceRegistration$$EnhancerBySpringCGLIB$$f119152a.bind(<generated>) [spring-cloud-consul-discovery-2.0.0.RC1.jar:2.0.0.RC1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_161]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:264) [spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:182) [spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:144) [spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) [spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) [spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) [spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:400) [spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:354) [spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:164) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553) [spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at com.test.consulretrydemo.ConsulRetryDemoApplication.main(ConsulRetryDemoApplication.java:14) [classes/:na]
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8500 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:221) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140) ~[httpclient-4.5.5.jar:4.5.5]
	at com.ecwid.consul.transport.AbstractHttpTransport.executeRequest(AbstractHttpTransport.java:61) ~[consul-api-1.3.1.jar:na]
	... 40 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_161]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_161]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_161]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_161]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_161]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_161]
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.5.jar:4.5.5]
	... 52 common frames omitted

2018-05-08 13:02:30.105  INFO 5699 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2018-05-08 13:02:30.114  WARN 5699 --- [ost-startStop-1] o.a.c.loader.WebappClassLoaderBase       : The web application [ROOT] appears to have started a thread named [spring.cloud.inetutils] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
 java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)
2018-05-08 13:02:30.126  INFO 5699 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-05-08 13:02:30.132 ERROR 5699 --- [           main] o.s.boot.SpringApplication               : Application run failed

com.ecwid.consul.transport.TransportException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8500 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
	at com.ecwid.consul.transport.AbstractHttpTransport.executeRequest(AbstractHttpTransport.java:77) ~[consul-api-1.3.1.jar:na]
	at com.ecwid.consul.transport.AbstractHttpTransport.makePutRequest(AbstractHttpTransport.java:41) ~[consul-api-1.3.1.jar:na]
	at com.ecwid.consul.v1.ConsulRawClient.makePutRequest(ConsulRawClient.java:135) ~[consul-api-1.3.1.jar:na]
	at com.ecwid.consul.v1.agent.AgentConsulClient.agentServiceRegister(AgentConsulClient.java:273) ~[consul-api-1.3.1.jar:na]
	at com.ecwid.consul.v1.ConsulClient.agentServiceRegister(ConsulClient.java:309) ~[consul-api-1.3.1.jar:na]
	at org.springframework.cloud.consul.serviceregistry.ConsulServiceRegistry.register(ConsulServiceRegistry.java:64) ~[spring-cloud-consul-discovery-2.0.0.RC1.jar:2.0.0.RC1]
	at org.springframework.cloud.consul.serviceregistry.ConsulServiceRegistry.register(ConsulServiceRegistry.java:41) ~[spring-cloud-consul-discovery-2.0.0.RC1.jar:2.0.0.RC1]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.register(AbstractAutoServiceRegistration.java:209) ~[spring-cloud-commons-2.0.0.RC1.jar:2.0.0.RC1]
	at org.springframework.cloud.consul.serviceregistry.ConsulAutoServiceRegistration.register(ConsulAutoServiceRegistration.java:78) ~[spring-cloud-consul-discovery-2.0.0.RC1.jar:2.0.0.RC1]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.start(AbstractAutoServiceRegistration.java:108) ~[spring-cloud-commons-2.0.0.RC1.jar:2.0.0.RC1]
	at org.springframework.cloud.consul.serviceregistry.ConsulAutoServiceRegistration.start(ConsulAutoServiceRegistration.java:68) ~[spring-cloud-consul-discovery-2.0.0.RC1.jar:2.0.0.RC1]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.bind(AbstractAutoServiceRegistration.java:73) ~[spring-cloud-commons-2.0.0.RC1.jar:2.0.0.RC1]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration$$FastClassBySpringCGLIB$$e099d3fe.invoke(<generated>) ~[spring-cloud-commons-2.0.0.RC1.jar:2.0.0.RC1]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:747) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke(AnnotationAwareRetryOperationsInterceptor.java:156) ~[spring-retry-1.2.2.RELEASE.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.cloud.consul.serviceregistry.ConsulAutoServiceRegistration$$EnhancerBySpringCGLIB$$f119152a.bind(<generated>) ~[spring-cloud-consul-discovery-2.0.0.RC1.jar:2.0.0.RC1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_161]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:264) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:182) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:144) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:400) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:354) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:164) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at com.test.consulretrydemo.ConsulRetryDemoApplication.main(ConsulRetryDemoApplication.java:14) [classes/:na]
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8500 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:221) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140) ~[httpclient-4.5.5.jar:4.5.5]
	at com.ecwid.consul.transport.AbstractHttpTransport.executeRequest(AbstractHttpTransport.java:61) ~[consul-api-1.3.1.jar:na]
	... 40 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_161]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_161]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_161]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_161]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_161]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_161]
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.5.jar:4.5.5]
	... 52 common frames omitted

2018-05-08 13:02:30.133  INFO 5699 --- [           main] ConfigServletWebServerApplicationContext : Closing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@4f3bbf68: startup date [Tue May 08 13:02:26 EEST 2018]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@3f56875e
2018-05-08 13:02:30.136  INFO 5699 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2018-05-08 13:02:30.136  INFO 5699 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans

Process finished with exit code 1
```

**Comment by huodon** [comment]
`org.springframework.cloud.consul.serviceregistry.ConsulAutoServiceRegistration#start()`  method has not been auto execute in my code. After the manual execution `start()`, it will register successfully.

**Comment by afayes** [comment]
I am not able to get the retry to work either.
Versions used:
Spring Boot - 2.0.3.RELEASE
Spring Cloud - Finchley.RC1

My config is similar to @nazar-mykolyshyn's demo code
spring-retry and spring-boot-starter-aop are added to the classpath.

**Comment by nazar-mykolyshyn** [comment]
Updated demo project to the latest released version of Spring Cloud:
Spring Boot - 2.0.3.RELEASE
Spring Cloud - Finchley.RELEASE
Retry still is not working.

Added possible workaround (just team thoughts - we didn't use it for production and didn't investigate consequences).
But if I create custom "consulAutoServiceRegistration" bean with `@Retryable` on overridden 'bind()' method then retry is catching ConnectException and applies retry configuration as many times as I configured in properties.

```
=== ConsulAutoServiceRegistrationCustom.java ===

public class ConsulAutoServiceRegistrationCustom extends ConsulAutoServiceRegistration {

  public ConsulAutoServiceRegistrationCustom(
      ConsulServiceRegistry serviceRegistry,
      AutoServiceRegistrationProperties autoServiceRegistrationProperties,
      ConsulDiscoveryProperties properties,
      ConsulAutoRegistration registration) {
    super(serviceRegistry, autoServiceRegistrationProperties, properties, registration);
  }

  @Override
  @Retryable(interceptor = "consulRetryInterceptor")
  public void bind(WebServerInitializedEvent event) {
    super.bind(event);
  }
}

=== CustomSettings.java ===

@Bean
  public ConsulAutoServiceRegistration consulAutoServiceRegistration(
      ConsulServiceRegistry registry,
      AutoServiceRegistrationProperties autoServiceRegistrationProperties,
      ConsulDiscoveryProperties properties,
      ConsulAutoRegistration consulRegistration) {
    return new ConsulAutoServiceRegistrationCustom(registry,
        autoServiceRegistrationProperties, properties, consulRegistration);
  }

```
Full code in separate branch https://github.com/nazar-mykolyshyn/consul-retry-demo/tree/workaround

**Comment by spencergibb** [comment]
Closing this due to inactivity. Please re-open if there's more to discuss.

**Comment by afayes** [comment]
Would prefer that the issue is not closed unless fixed, otherwise it will never get fixed..

**Comment by michelfigueiredojava** [comment]
> Updated demo project to the latest released version of Spring Cloud:
> Spring Boot - 2.0.3.RELEASE
> Spring Cloud - Finchley.RELEASE
> Retry still is not working.
> 
> Added possible workaround (just team thoughts - we didn't use it for production and didn't investigate consequences).
> But if I create custom "consulAutoServiceRegistration" bean with `@Retryable` on overridden 'bind()' method then retry is catching ConnectException and applies retry configuration as many times as I configured in properties.
> 
> ```
> === ConsulAutoServiceRegistrationCustom.java ===
> 
> public class ConsulAutoServiceRegistrationCustom extends ConsulAutoServiceRegistration {
> 
>   public ConsulAutoServiceRegistrationCustom(
>       ConsulServiceRegistry serviceRegistry,
>       AutoServiceRegistrationProperties autoServiceRegistrationProperties,
>       ConsulDiscoveryProperties properties,
>       ConsulAutoRegistration registration) {
>     super(serviceRegistry, autoServiceRegistrationProperties, properties, registration);
>   }
> 
>   @Override
>   @Retryable(interceptor = "consulRetryInterceptor")
>   public void bind(WebServerInitializedEvent event) {
>     super.bind(event);
>   }
> }
> 
> === CustomSettings.java ===
> 
> @Bean
>   public ConsulAutoServiceRegistration consulAutoServiceRegistration(
>       ConsulServiceRegistry registry,
>       AutoServiceRegistrationProperties autoServiceRegistrationProperties,
>       ConsulDiscoveryProperties properties,
>       ConsulAutoRegistration consulRegistration) {
>     return new ConsulAutoServiceRegistrationCustom(registry,
>         autoServiceRegistrationProperties, properties, consulRegistration);
>   }
> ```
> 
> Full code in separate branch https://github.com/nazar-mykolyshyn/consul-retry-demo/tree/workaround

I cloned and executed this project but unfortunately it didn't do what it is supposed to do.

**Comment by michelfigueiredojava** [comment]
> Would prefer that the issue is not closed unless fixed, otherwise it will never get fixed..

I agree with you. I am trying to use consul as a discovery solution but stuck on this problem now.

**Comment by spencergibb** [comment]
The fix is not in the versions you mentioned but in the versions tagged

**Comment by michelfigueiredojava** [comment]
> versions tagged

sorry, which version ?

**Comment by spencergibb** [comment]
Greenwich.RELEASE and Finchley.SR3

**Comment by michelfigueiredojava** [comment]
well this is the version I am using, it is not working for me

I have a consul docker container working, when I startup my app it is well registered in consul catalog, then I stop consul docker container, my app throws lots of exceptions, I start consul docker container, the exceptions are gone but my app is not registered again in consul catalog

I cloned that repo and changed some files to be like this:

```
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.1.5.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
		<spring-cloud.version>Greenwich.RELEASE</spring-cloud.version>
	</properties>

```


```

spring:
  application:
    name: consul-retry-demo
  cloud:
    consul:
      host: localhost
      port: 8500
      retry:
        initial-interval: 1000
        max-attempts: 70
        max-interval: 2000
        multiplier: 1.1
server:
  port: 8083

```

**Comment by spencergibb** [comment]
That's not retry, that's reregister, there is an open issue for that.

**Comment by jjacob27** [comment]
Can you give the link for the reregister issue?

**Comment by lkowdampalli** [comment]
Hello @spencergibb can you please point us to the issue link for the reregister vs retry? Or if this issue has been resolved can you confirm what is the fix for consul retry not working ?

**Comment by making** [comment]
@lkowdampalli it's work in progress https://github.com/spring-cloud/spring-cloud-consul/pull/691
