### ISSUE TITLE
Reload properties raised an exception

### ISSUE THREAD

**Issue by jmirc** [spring-cloud/spring-cloud-consul#42]
When I try to refresh the properties using curl ```curl localhost:8080/refresh -d {} ``` I got an exception.

```
java.lang.NullPointerException: null
	at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.decrypt(EnvironmentDecryptApplicationInitializer.java:127)
	at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.decrypt(EnvironmentDecryptApplicationInitializer.java:116)
	at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.initialize(EnvironmentDecryptApplicationInitializer.java:80)
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:567)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139)
	at org.springframework.cloud.bootstrap.config.RefreshEndpoint.addConfigFilesToEnvironment(RefreshEndpoint.java:86)
	at org.springframework.cloud.bootstrap.config.RefreshEndpoint.refresh(RefreshEndpoint.java:72)
	at org.springframework.cloud.bootstrap.config.RefreshEndpoint.invoke(RefreshEndpoint.java:121)
	at org.springframework.cloud.bootstrap.config.RefreshEndpoint.invoke(RefreshEndpoint.java:47)

```

The issue is related to how the properties are loaded from the consul server by the class named ```ConsulPropertySource```.  The method ```init``` adds in the ```properties``` consul key or folder. No check to verify if the key is a folder is done. In this case, the name of the key is set to "" (empty) so when the refresh is called an exception is thrown.

**Comment by spencergibb** [comment]
@jmirc I was unable to reproduce, but added a check to make sure the key has text.  Will you try a snapshot when it is built?

**Comment by jmirc** [comment]
I tested and it works. Thanks
