### ISSUE TITLE
spring-cloud-starter-consul-bus Not working with default config

### ISSUE THREAD

**Issue by vova-uvarov** [spring-cloud/spring-cloud-consul#468]
```
2018-11-12 00:22:41.062 ERROR 14288 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:807) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:794) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:324) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at com.example.event.sender.TestEventSenderApplication.main(TestEventSenderApplication.java:20) [classes/:na]
Caused by: org.springframework.messaging.MessageHandlingException: error occurred in message handler [org.springframework.cloud.consul.binder.ConsulSendingHandler@2ec3633f]; nested exception is java.lang.ClassCastException: [B cannot be cast to java.lang.String
	at org.springframework.integration.support.utils.IntegrationUtils.wrapInHandlingExceptionIfNecessary(IntegrationUtils.java:189) ~[spring-integration-core-5.1.0.RELEASE.jar:5.1.0.RELEASE]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:179) ~[spring-integration-core-5.1.0.RELEASE.jar:5.1.0.RELEASE]
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115) ~[spring-integration-core-5.1.0.RELEASE.jar:5.1.0.RELEASE]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133) ~[spring-integration-core-5.1.0.RELEASE.jar:5.1.0.RELEASE]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106) ~[spring-integration-core-5.1.0.RELEASE.jar:5.1.0.RELEASE]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73) ~[spring-integration-core-5.1.0.RELEASE.jar:5.1.0.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:451) ~[spring-integration-core-5.1.0.RELEASE.jar:5.1.0.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:400) ~[spring-integration-core-5.1.0.RELEASE.jar:5.1.0.RELEASE]
	at org.springframework.cloud.bus.BusAutoConfiguration.acceptLocal(BusAutoConfiguration.java:121) ~[spring-cloud-bus-2.1.0.M1.jar:2.1.0.M1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:261) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:180) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:142) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:398) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:355) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at com.example.event.sender.TestEventSenderApplication.run(TestEventSenderApplication.java:25) [classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	... 5 common frames omitted
Caused by: java.lang.ClassCastException: [B cannot be cast to java.lang.String
	at org.springframework.cloud.consul.binder.ConsulSendingHandler.handleMessageInternal(ConsulSendingHandler.java:52) ~[spring-cloud-consul-binder-2.1.0.M1.jar:2.1.0.M1]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:169) ~[spring-integration-core-5.1.0.RELEASE.jar:5.1.0.RELEASE]
	... 26 common frames omitted
```

i use simple configuration for send remote event by cloud bus and consul.
create simple example https://github.com/vova-uvarov/consul-bus-error

based on stacktrace i see code:
```java
		Object payload = message.getPayload();
		// TODO: support headers
		// TODO: support consul event filters: NodeFilter, ServiceFilter, TagFilter
		Response<Event> event = consul.eventFire(this.eventName, (String) payload,
				new EventParams(), QueryParams.DEFAULT);
```

problem in  (String) payload. this payload is byte[]

**Comment by spencergibb** [comment]
Duplicates #458

**Comment by dean588** [comment]
Hi ,

I try to fire an event using below code but it doesn't work.Any suggestions?I use spring boot 2.3.1  version and Hoxton.SR6 spring-cloud -version and Java 8.

EventParams eventParams = new EventParams();
eventParams.setName("ms-event");
Response<Event> response = com.ecwid.consul.v1.ConsulClient.consulClient.eventFire("test", "122222", eventParams, QueryParams.DEFAULT);

ERROR LOG
[pool-1-thread-1] o.s.c.c.b.ConsulInboundMessageProducer   : Error getting consul events: error occurred in message handler [org.springframework.cloud.consul.binder.ConsulSendingHandler@7e5b5d76]; nested exception is java.lang.ClassCastException: [B cannot be cast to java.lang.String
