### ISSUE TITLE
Consul Error at com.ecwid.consul.v1.OperationException

### ISSUE THREAD

**Issue by sangramgh01** [spring-cloud/spring-cloud-consul#476]
Hi While using spring cloud in my application when one microservice is trying to get the end point of other i got the below exception.
```
com.ecwid.consul.v1.OperationException: null
	at com.ecwid.consul.v1.health.HealthConsulClient.getHealthServices(HealthConsulClient.java:96) ~[consul-api-1.1.10.jar!/:na]
	at com.ecwid.consul.v1.health.HealthConsulClient.getHealthServices(HealthConsulClient.java:80) ~[consul-api-1.1.10.jar!/:na]
	at com.ecwid.consul.v1.ConsulClient.getHealthServices(ConsulClient.java:329) ~[consul-api-1.1.10.jar!/:na]
	at org.springframework.cloud.consul.discovery.ConsulDiscoveryClient.addInstancesToList(ConsulDiscoveryClient.java:128) ~[spring-cloud-consul-discovery-1.0.1.RELEASE.jar!/:1.0.1.RELEASE]
	at org.springframework.cloud.consul.discovery.ConsulDiscoveryClient.getInstances(ConsulDiscoveryClient.java:121) ~[spring-cloud-consul-discovery-1.0.1.RELEASE.jar!/:1.0.1.RELEASE]
	at org.springframework.cloud.consul.discovery.ConsulDiscoveryClient.getInstances(ConsulDiscoveryClient.java:114) ~[spring-cloud-consul-discovery-1.0.1.RELEASE.jar!/:1.0.1.RELEASE]
```
Please check whether this issue is due to consul is down or something else.

Thanks,
Sangram

**Comment by spencergibb** [comment]
There's not enough information to diagnose the problem. What versions of spring cloud and spring boot are you using? Consul version? Configuration? Steps to reproduce?

**Comment by sangramgh01** [comment]
I am using below versions
Spring boot:1.3.5
spring-cloud-starter-consul-discovery:1.0.1.RELEASE
Spring framework: 4.3
There is no specific way to reproduce the issue.
It was failed  when i try to call one microservice to other for that perticular moment.
Next time i did retry.It was worked.
So, my question is here is it due to consul connectivity issue or something else.

Thanks,
Sangram

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
