### ISSUE TITLE
MalformedInputException while reading none ISO charsets value from consul

### ISSUE THREAD

**Issue by BeamLiu** [spring-cloud/spring-cloud-consul#577]
yml config in consul like:
```
emop:
  additionalInformation: |
    {"internal_trusted_rest_url":"http://${emop.customerCode}-workflow-etl/workflow-etl/public/tc/login","customerCode":"${emop.customerCode}","homepage":"/workflow-monitor/#/workflow-job-list","authorized_services":[{"name":"Workflow Monitor","uri":"/workflow-monitor/#/workflow-job-list"},{"name":"IT资产监控","uri":"/assert-monitor/#/monitor-overview"}]}
```

Here is the related stacktrace during spring boot startup:
```
2019-08-18 21:41:10.497 ERROR 23964 --- [           main] o.s.c.c.c.ConsulPropertySourceLocator    : Fail fast is set and there was an error reading configuration from consul.
org.yaml.snakeyaml.error.YAMLException: java.nio.charset.MalformedInputException: Input length = 1
        at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:254)
        at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:160)
        at org.yaml.snakeyaml.scanner.ScannerImpl.scanPlain(ScannerImpl.java:2003)
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchPlain(ScannerImpl.java:1046)
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:401)
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226)
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:557)
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157)
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:227)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154)
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:249)
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:240)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:228)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154)
        at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:84)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:123)
        at org.yaml.snakeyaml.Yaml$1.next(Yaml.java:547)
        at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:160)
        at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:138)
        at org.springframework.beans.factory.config.YamlPropertiesFactoryBean.createProperties(YamlPropertiesFactoryBean.java:133)
        at org.springframework.beans.factory.config.YamlPropertiesFactoryBean.getObject(YamlPropertiesFactoryBean.java:113)
        at org.springframework.cloud.consul.config.ConsulPropertySource.generateProperties(ConsulPropertySource.java:163)
        at org.springframework.cloud.consul.config.ConsulPropertySource.parseValue(ConsulPropertySource.java:134)
        at org.springframework.cloud.consul.config.ConsulPropertySource.parsePropertiesWithNonKeyValueFormat(ConsulPropertySource.java:123)
        at org.springframework.cloud.consul.config.ConsulPropertySource.init(ConsulPropertySource.java:79)
        at org.springframework.cloud.consul.config.ConsulPropertySourceLocator.create(ConsulPropertySourceLocator.java:166)
        at org.springframework.cloud.consul.config.ConsulPropertySourceLocator.locate(ConsulPropertySourceLocator.java:132)
        at org.springframework.cloud.consul.config.ConsulPropertySourceLocator$$FastClassBySpringCGLIB$$b35ebf8.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:747)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:91)
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287)
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:164)
        at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:118)
        at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke(AnnotationAwareRetryOperationsInterceptor.java:153)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
        at org.springframework.cloud.consul.config.ConsulPropertySourceLocator$$EnhancerBySpringCGLIB$$28576ae2.locate(<generated>)
        at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:94)
        at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:633)
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:373)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:325)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243)
        at com.eingsoft.emop.Application.main(Application.java:72)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.nio.charset.MalformedInputException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:125)
        at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:223)
        ... 55 more
```
It seems `org.springframework.cloud.consul.config.ConsulPropertySource.generateProperties()` is using default charset to convert string to byte, I think it is a bug, it would specify utf-8 encoding explicitly here
```
else if (format == YAML) {
			final YamlPropertiesFactoryBean yaml = new YamlPropertiesFactoryBean();
			yaml.setResources(new ByteArrayResource(value.getBytes()));

			return yaml.getObject();
		}
```
according to my OS locale, my jvm default charset is GBK
```
java.nio.charset.Charset.defaultCharset();  //output is GBK
```
and later `org.springframework.beans.factory.config.YamlProcessor.process()` is handling the stream through unicode code
```
Reader reader = new UnicodeReader(resource.getInputStream());
```
Currently I am using a workaround to add jvm startup parameter `-Dfile.encoding=utf-8` to change the default charset.

**Comment by ouyangyaxiong** [comment]
PROPERTIES also need to use utf-8

  protected Properties generateProperties(String value, Format format) {
        Properties props = new Properties();
        if (format == Format.PROPERTIES) {
            try {
**// bug here**
                props.load(new ByteArrayInputStream(value.getBytes("ISO-8859-1")));
                return props;
            } catch (IOException var5) {
                throw new IllegalArgumentException(value + " can't be encoded using ISO-8859-1");
            }
        } else if (format == Format.YAML) {
            YamlPropertiesFactoryBean yaml = new YamlPropertiesFactoryBean();
            yaml.setResources(new Resource[]{new ByteArrayResource(value.getBytes())});
            return yaml.getObject();
        } else {
            return props;
        }
    }
