### ISSUE TITLE
ConsulAutoServiceRegistration fails when management server port is set to 0 in Spring Boot 2

### ISSUE THREAD

**Issue by jg845** [spring-cloud/spring-cloud-consul#595]
Running Spring Cloud Consul 2.1.3 and Spring Boot 2
Consul instance listening on port 8500
Configuring Spring Boot to run management server on random port through `management.server.port: 0` configuration.

During Consul service auto-registration registration fails due to trying to register the management server on port 0. Stacktrace:
```
java.lang.IllegalArgumentException: createCheck port must be greater than 0
	at org.springframework.util.Assert.isTrue(Assert.java:118) ~[spring-core-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	at org.springframework.cloud.consul.serviceregistry.ConsulAutoRegistration.createCheck(ConsulAutoRegistration.java:236) ~[spring-cloud-consul-discovery-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.cloud.consul.serviceregistry.ConsulAutoRegistration.setCheck(ConsulAutoRegistration.java:129) ~[spring-cloud-consul-discovery-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.cloud.consul.serviceregistry.ConsulAutoRegistration.initializePort(ConsulAutoRegistration.java:336) ~[spring-cloud-consul-discovery-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.cloud.consul.serviceregistry.ConsulAutoServiceRegistration.getRegistration(ConsulAutoServiceRegistration.java:58) ~[spring-cloud-consul-discovery-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.cloud.consul.serviceregistry.ConsulAutoServiceRegistration.getRegistration(ConsulAutoServiceRegistration.java:33) ~[spring-cloud-consul-discovery-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.start(AbstractAutoServiceRegistration.java:137) ~[spring-cloud-commons-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.cloud.consul.serviceregistry.ConsulAutoServiceRegistration.start(ConsulAutoServiceRegistration.java:73) ~[spring-cloud-consul-discovery-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.cloud.consul.serviceregistry.ConsulAutoServiceRegistrationListener.onApplicationEvent(ConsulAutoServiceRegistrationListener.java:63) ~[spring-cloud-consul-discovery-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:165) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140) [spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
	at com.example.demo.DemoApplication.main(DemoApplication.java:19) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_211]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_211]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [demo-0.0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [demo-0.0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [demo-0.0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) [demo-0.0.1-SNAPSHOT.jar:na]
```

Believe this is happening because Consul auto-registration is occurring after the application server but before the management server is created, so the latter hasn't been assigned a non-zero port.

Saw relevant issue #555 but fix introduced there doesn't solve this issue.

Error can be reproduced my running demo here: https://github.com/jg845/spring-cloud-consul-issue

**Comment by spencergibb** [comment]
#555 is still open. This is a duplicate.
