### ISSUE TITLE
Covert java Duration to consul compatible interval string

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-consul#614]
https://golang.org/pkg/time/#ParseDuration

**Comment by UkrainianCitizen** [comment]
@spencergibb I could do this.

**Comment by spencergibb** [comment]
PRs welcome

**Comment by UkrainianCitizen** [comment]
I'm trying to build the project and the Maven install fails on spring-cloud-consul-core with failed test in `org.springframework.cloud.consul.ConsulHealthIndicatorUpTest`. Could you kindly share ideas why does this happen?

**Comment by spencergibb** [comment]
you must be running consul during the build. This is what I typically do first
```
rm -rf /tmp/consul && ./src/main/bash/local_run_consul.sh
```

**Comment by spencergibb** [comment]
That's not very friendly because you need to have a specific version and those scripts work on linux, maybe on a mac and not on windows.

**Comment by spencergibb** [comment]
I've opened #623 to investigate using testcontainers

**Comment by UkrainianCitizen** [comment]
@spencergibb Thanks! Could you elaborate what do you mean by running consul? As far as I am concerned, it should be ran from `local_run_consul.sh`, given the comments hereabove, but the command `consul` doesn't exist for me.

Apart from that, after proceceding to the next window after adding checktyle.xml, header and suppresions file, in the parent Checkstyle window(in IDEA) I am getting this exception 
```
com.puppycrawl.tools.checkstyle.api.CheckstyleException: unable to parse configuration stream
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:321)
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:283)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.infernus.idea.checkstyle.service.cmd.OpLoadConfiguration.loadConfigurationForCheckstyle825AndAbove(OpLoadConfiguration.java:188)
	at org.infernus.idea.checkstyle.service.cmd.OpLoadConfiguration.callLoadConfiguration(OpLoadConfiguration.java:156)
	at org.infernus.idea.checkstyle.service.cmd.OpLoadConfiguration.execute(OpLoadConfiguration.java:139)
	at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.loadConfig(OpCreateChecker.java:91)
	at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.execute(OpCreateChecker.java:54)
	at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.execute(OpCreateChecker.java:26)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:130)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.createChecker(CheckstyleActionsImpl.java:60)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.createChecker(CheckstyleActionsImpl.java:51)
	at org.infernus.idea.checkstyle.checker.CheckerFactoryWorker.run(CheckerFactoryWorker.java:46)
Caused by: org.xml.sax.SAXException: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Property ${checkstyle.additional.suppressions.file} has not been set
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Property ${checkstyle.additional.suppressions.file} has not been set
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader$InternalLoader.startElement(ConfigurationLoader.java:525)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.dtd.XMLDTDValidator.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at com.puppycrawl.tools.checkstyle.XmlLoader.parseInputSource(XmlLoader.java:84)
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.parseInputSource(ConfigurationLoader.java:196)
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:311)
	... 15 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Property ${checkstyle.additional.suppressions.file} has not been set
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.replaceProperties(ConfigurationLoader.java:372)
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.access$500(ConfigurationLoader.java:51)
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader$InternalLoader.startElement(ConfigurationLoader.java:520)
	... 29 more

```

**Comment by spencergibb** [comment]
You have to have Consul installed first right now. See Travis install Consul for what we do on Linux

**Comment by UkrainianCitizen** [comment]
Hi, now I am getting this with running consul.
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.842 s
[INFO] Finished at: 2020-06-07T19:20:08+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project spring-cloud-consul-core: Compilation failure: Compilation failure:
[ERROR] /home/spring-cloud-consul/spring-cloud-consul-core/src/test/java/org/springframework/cloud/consul/ConsulHealthIndicatorUpTest.java:[19,17] cannot find symbol
[ERROR]   symbol:   class Test
[ERROR]   location: package org.junit
[ERROR] /home/spring-cloud-consul/spring-cloud-consul-core/src/test/java/org/springframework/cloud/consul/ConsulHealthIndicatorUpTest.java:[20,24] package org.junit.runner does not exist
```
