### ISSUE TITLE
Only ConsulDiscoveryProperties private constructor invoked - NPE on hostInfo property

### ISSUE THREAD

**Issue by tuxdevelop** [spring-cloud/spring-cloud-consul#683]
**Describe the bug**

**Stack:**

- Spring Boot:  2.4.0
- Spring Cloud Dependencies: 2020.0.0-M5 / 2020.0.0-M6
- Spring Cloud Consul: 3.0.0-M5 / 3.0.0-M6
- Spring Cloud Config: 3.0.0-M5 / 3.0.0-M6

```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-consul-discovery</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-config</artifactId>
        </dependency>

```
**Description**

When using `spring-cloud-consul-discovery` and spring-cloud-config, the private constructor of `ConsulDiscoveryProperties` is invoked and not the public one with `InetUtils` as parameter. This causes in a not configured `hostInfo` property. When calling the setter of `hostname` property of `ConsulDiscoveryProperties`, `this.hostInfo.override = true;`is invoked and a NPE is thrown.

**Stack Trace**

```
org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'spring.cloud.consul.discovery' to org.springframework.cloud.consul.discovery.ConsulDiscoveryProperties
	at org.springframework.boot.context.properties.bind.Binder.handleBindError(Binder.java:363)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:323)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:308)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:238)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:199)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:186)
	at org.springframework.cloud.consul.discovery.configclient.ConsulConfigServerBootstrapper.lambda$intitialize$3(ConsulConfigServerBootstrapper.java:57)
	at org.springframework.cloud.consul.discovery.configclient.ConsulConfigServerBootstrapper$$Lambda$327/000000000000000000.get(Unknown Source)
	at org.springframework.boot.DefaultBootstrapContext.getInstance(DefaultBootstrapContext.java:119)
	at org.springframework.boot.DefaultBootstrapContext.getOrElseThrow(DefaultBootstrapContext.java:111)
	at org.springframework.boot.DefaultBootstrapContext.get(DefaultBootstrapContext.java:88)
	at org.springframework.cloud.consul.discovery.configclient.ConsulConfigServerBootstrapper.lambda$intitialize$4(ConsulConfigServerBootstrapper.java:63)
	at org.springframework.cloud.consul.discovery.configclient.ConsulConfigServerBootstrapper$$Lambda$328/000000000000000000.onApplicationEvent(Unknown Source)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:203)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:196)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:170)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:148)
	at org.springframework.boot.DefaultBootstrapContext.close(DefaultBootstrapContext.java:131)
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:392)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:325)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298)
	at org.example.TestApp.main(TestApp.java:14)
Caused by: java.lang.IllegalStateException: Unable to set value for property hostname
	at org.springframework.boot.context.properties.bind.JavaBeanBinder$BeanProperty.setValue(JavaBeanBinder.java:357)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:98)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:80)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:56)
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$5(Binder.java:451)
	at org.springframework.boot.context.properties.bind.Binder$$Lambda$183/000000000000000000.get(Unknown Source)
	at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:571)
	at org.springframework.boot.context.properties.bind.Binder$Context.withDataObject(Binder.java:557)
	at org.springframework.boot.context.properties.bind.Binder$Context.access$300(Binder.java:512)
	at org.springframework.boot.context.properties.bind.Binder.bindDataObject(Binder.java:449)
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:390)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:319)
	... 21 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder$BeanProperty.setValue(JavaBeanBinder.java:354)
	... 32 common frames omitted
Caused by: java.lang.NullPointerException: null
	at org.springframework.cloud.consul.discovery.ConsulDiscoveryProperties.setHostname(ConsulDiscoveryProperties.java:235)
	... 37 common frames omitted
14:29:08.130 [main] ERROR o.s.b.d.LoggingFailureAnalysisReporter - 
```

**Sample**

Just create a Spring Boot application with the given dependencies above and set the property 

```
spring:
  application:
    name: issue-app
  cloud:
    config:
      enabled: true
      discovery:
        enabled: true
    consul:
      discovery:
        hostname: 'some-host-name'

```

Thanks,

Marcel

**Comment by spencergibb** [comment]
Is this still a problem with 3.0.0?

**Comment by tuxdevelop** [comment]
Hi @spencergibb,
the problem still exists with the described scenario
