### ISSUE TITLE
Post Modifying the Value from Consul UI not reflecting in Sping Consul

### ISSUE THREAD

**Issue by jgeekgd** [spring-cloud/spring-cloud-consul#804]
The spring cloud able to access properties from consul kv but once the values are modified using consul UI spring cloud application 
gives below error:

```
2022-12-16T11:32:57.650+05:30  WARN 30612 --- [undedElastic-12] o.s.c.h.RefreshScopeHealthIndicator      : Health check failed

org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'httpClientProperties': Could not bind properties to 'HttpClientProperties' : prefix=spring.cloud.gateway.httpclient, ignoreInvalidFields=false, ignoreUnknownFields=true
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.bind(ConfigurationPropertiesBindingPostProcessor.java:92) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:78) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:420) ~[spring-beans-6.0.2.jar:6.0.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1743) ~[spring-beans-6.0.2.jar:6.0.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:411) ~[spring-beans-6.0.2.jar:6.0.2]
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.rebind(ConfigurationPropertiesRebinder.java:138) ~[spring-cloud-context-4.0.0-RC2.jar:4.0.0-RC2]
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.rebind(ConfigurationPropertiesRebinder.java:97) ~[spring-cloud-context-4.0.0-RC2.jar:4.0.0-RC2]
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.rebind(ConfigurationPropertiesRebinder.java:85) ~[spring-cloud-context-4.0.0-RC2.jar:4.0.0-RC2]
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.onApplicationEvent(ConfigurationPropertiesRebinder.java:170) ~[spring-cloud-context-4.0.0-RC2.jar:4.0.0-RC2]
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.onApplicationEvent(ConfigurationPropertiesRebinder.java:53) ~[spring-cloud-context-4.0.0-RC2.jar:4.0.0-RC2]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:413) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:370) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.cloud.context.refresh.ContextRefresher.refreshEnvironment(ContextRefresher.java:103) ~[spring-cloud-context-4.0.0-RC2.jar:4.0.0-RC2]
	at org.springframework.cloud.context.refresh.ContextRefresher.refresh(ContextRefresher.java:94) ~[spring-cloud-context-4.0.0-RC2.jar:4.0.0-RC2]
	at org.springframework.cloud.endpoint.event.RefreshEventListener.handle(RefreshEventListener.java:72) ~[spring-cloud-context-4.0.0-RC2.jar:4.0.0-RC2]
	at org.springframework.cloud.endpoint.event.RefreshEventListener.onApplicationEvent(RefreshEventListener.java:61) ~[spring-cloud-context-4.0.0-RC2.jar:4.0.0-RC2]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:413) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:370) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.cloud.consul.config.ConfigWatch.watchConfigKeyValues(ConfigWatch.java:173) ~[spring-cloud-consul-config-4.0.0-RC2.jar:4.0.0-RC2]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.0.2.jar:6.0.2]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'spring.cloud.gateway.httpclient.ssl.key-manager-factory.provider' to java.security.Provider
	at org.springframework.boot.context.properties.bind.Binder.handleBindError(Binder.java:387) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:347) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$4(Binder.java:472) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.ValueObjectBinder$ConstructorParameter.bind(ValueObjectBinder.java:314) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.ValueObjectBinder.bind(ValueObjectBinder.java:76) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$5(Binder.java:476) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:590) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder$Context.withDataObject(Binder.java:576) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.bindDataObject(Binder.java:474) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:414) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:343) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$4(Binder.java:472) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:98) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:86) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:62) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$5(Binder.java:476) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:590) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder$Context.withDataObject(Binder.java:576) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.bindDataObject(Binder.java:474) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:414) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:343) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$4(Binder.java:472) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:98) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:86) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:62) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$5(Binder.java:476) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:590) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder$Context.withDataObject(Binder.java:576) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.bindDataObject(Binder.java:474) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:414) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:343) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:332) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:262) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:249) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.ConfigurationPropertiesBinder.bind(ConfigurationPropertiesBinder.java:94) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.bind(ConfigurationPropertiesBindingPostProcessor.java:89) ~[spring-boot-3.0.0.jar:3.0.0]
	... 31 common frames omitted
Caused by: java.lang.IllegalArgumentException: Could not instantiate Map type: java.security.Provider
	at org.springframework.core.CollectionFactory.createMap(CollectionFactory.java:321) ~[spring-core-6.0.2.jar:6.0.2]
	at org.springframework.core.CollectionFactory.createMap(CollectionFactory.java:265) ~[spring-core-6.0.2.jar:6.0.2]
	at org.springframework.boot.context.properties.bind.MapBinder.bindAggregate(MapBinder.java:57) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.AggregateBinder.bind(AggregateBinder.java:56) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindAggregate$3(Binder.java:438) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:590) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.bindAggregate(Binder.java:438) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:399) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:343) ~[spring-boot-3.0.0.jar:3.0.0]
	... 65 common frames omitted
Caused by: java.lang.NoSuchMethodException: java.security.Provider.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3585) ~[na:na]
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2754) ~[na:na]
	at org.springframework.util.ReflectionUtils.accessibleConstructor(ReflectionUtils.java:185) ~[spring-core-6.0.2.jar:6.0.2]
	at org.springframework.core.CollectionFactory.createMap(CollectionFactory.java:318) ~[spring-core-6.0.2.jar:6.0.2]
	... 73 common frames omitted

2022-12-16T11:32:57.653+05:30 DEBUG 30612 --- [oundedElastic-7] .s.w.r.r.m.a.ResponseEntityResultHandler : [f0a55fe5-217] Using 'application/vnd.spring-boot.actuator.v3+json' given [text/plain, text/*, */*] and supported [application/vnd.spring-boot.actuator.v3+json, application/vnd.spring-boot.actuator.v2+json, application/json]
2022-12-16T11:32:57.653+05:30 DEBUG 30612 --- [oundedElastic-7] .s.w.r.r.m.a.ResponseEntityResultHandler : [f0a55fe5-217] 0..1 [org.springframework.boot.actuate.health.SystemHealth]
2022-12-16T11:32:57.653+05:30 DEBUG 30612 --- [oundedElastic-7] o.s.http.codec.json.Jackson2JsonEncoder  : [f0a55fe5-217] Encoding [org.springframework.boot.actuate.health.SystemHealth@4b2e8327]
2022-12-16T11:32:57.655+05:30 DEBUG 30612 --- [ctor-http-nio-2] o.s.w.s.adapter.HttpWebHandlerAdapter    : [f0a55fe5-217] Completed 503 SERVICE_UNAVAILABLE
2022-12-16T11:33:07.674+05:30 DEBUG 30612 --- [ctor-http-nio-3] o.s.w.s.adapter.HttpWebHandlerAdapter    : [dbb74de6-218] HTTP GET "/actuator/health"
2022-12-16T11:33:07.675+05:30 DEBUG 30612 --- [ctor-http-nio-3] .b.a.e.w.r.WebFluxEndpointHandlerMapping : [dbb74de6-218] Mapped to Actuator web endpoint 'health'
2022-12-16T11:33:07.676+05:30  WARN 30612 --- [oundedElastic-8] o.s.c.h.RefreshScopeHealthIndicator      : Health check failed

org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'httpClientProperties': Could not bind properties to 'HttpClientProperties' : prefix=spring.cloud.gateway.httpclient, ignoreInvalidFields=false, ignoreUnknownFields=true
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.bind(ConfigurationPropertiesBindingPostProcessor.java:92) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:78) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:420) ~[spring-beans-6.0.2.jar:6.0.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1743) ~[spring-beans-6.0.2.jar:6.0.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:411) ~[spring-beans-6.0.2.jar:6.0.2]
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.rebind(ConfigurationPropertiesRebinder.java:138) ~[spring-cloud-context-4.0.0-RC2.jar:4.0.0-RC2]
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.rebind(ConfigurationPropertiesRebinder.java:97) ~[spring-cloud-context-4.0.0-RC2.jar:4.0.0-RC2]
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.rebind(ConfigurationPropertiesRebinder.java:85) ~[spring-cloud-context-4.0.0-RC2.jar:4.0.0-RC2]
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.onApplicationEvent(ConfigurationPropertiesRebinder.java:170) ~[spring-cloud-context-4.0.0-RC2.jar:4.0.0-RC2]
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.onApplicationEvent(ConfigurationPropertiesRebinder.java:53) ~[spring-cloud-context-4.0.0-RC2.jar:4.0.0-RC2]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:413) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:370) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.cloud.context.refresh.ContextRefresher.refreshEnvironment(ContextRefresher.java:103) ~[spring-cloud-context-4.0.0-RC2.jar:4.0.0-RC2]
	at org.springframework.cloud.context.refresh.ContextRefresher.refresh(ContextRefresher.java:94) ~[spring-cloud-context-4.0.0-RC2.jar:4.0.0-RC2]
	at org.springframework.cloud.endpoint.event.RefreshEventListener.handle(RefreshEventListener.java:72) ~[spring-cloud-context-4.0.0-RC2.jar:4.0.0-RC2]
	at org.springframework.cloud.endpoint.event.RefreshEventListener.onApplicationEvent(RefreshEventListener.java:61) ~[spring-cloud-context-4.0.0-RC2.jar:4.0.0-RC2]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:413) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:370) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.cloud.consul.config.ConfigWatch.watchConfigKeyValues(ConfigWatch.java:173) ~[spring-cloud-consul-config-4.0.0-RC2.jar:4.0.0-RC2]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.0.2.jar:6.0.2]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'spring.cloud.gateway.httpclient.ssl.key-manager-factory.provider' to java.security.Provider
	at org.springframework.boot.context.properties.bind.Binder.handleBindError(Binder.java:387) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:347) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$4(Binder.java:472) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.ValueObjectBinder$ConstructorParameter.bind(ValueObjectBinder.java:314) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.ValueObjectBinder.bind(ValueObjectBinder.java:76) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$5(Binder.java:476) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:590) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder$Context.withDataObject(Binder.java:576) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.bindDataObject(Binder.java:474) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:414) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:343) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$4(Binder.java:472) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:98) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:86) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:62) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$5(Binder.java:476) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:590) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder$Context.withDataObject(Binder.java:576) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.bindDataObject(Binder.java:474) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:414) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:343) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$4(Binder.java:472) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:98) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:86) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:62) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$5(Binder.java:476) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:590) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder$Context.withDataObject(Binder.java:576) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.bindDataObject(Binder.java:474) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:414) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:343) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:332) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:262) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:249) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.ConfigurationPropertiesBinder.bind(ConfigurationPropertiesBinder.java:94) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.bind(ConfigurationPropertiesBindingPostProcessor.java:89) ~[spring-boot-3.0.0.jar:3.0.0]
	... 31 common frames omitted
Caused by: java.lang.IllegalArgumentException: Could not instantiate Map type: java.security.Provider
	at org.springframework.core.CollectionFactory.createMap(CollectionFactory.java:321) ~[spring-core-6.0.2.jar:6.0.2]
	at org.springframework.core.CollectionFactory.createMap(CollectionFactory.java:265) ~[spring-core-6.0.2.jar:6.0.2]
	at org.springframework.boot.context.properties.bind.MapBinder.bindAggregate(MapBinder.java:57) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.AggregateBinder.bind(AggregateBinder.java:56) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindAggregate$3(Binder.java:438) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:590) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.bindAggregate(Binder.java:438) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:399) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:343) ~[spring-boot-3.0.0.jar:3.0.0]
	... 65 common frames omitted
Caused by: java.lang.NoSuchMethodException: java.security.Provider.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3585) ~[na:na]
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2754) ~[na:na]
	at org.springframework.util.ReflectionUtils.accessibleConstructor(ReflectionUtils.java:185) ~[spring-core-6.0.2.jar:6.0.2]
	at org.springframework.core.CollectionFactory.createMap(CollectionFactory.java:318) ~[spring-core-6.0.2.jar:6.0.2]
	... 73 common frames omitted

2022-12-16T11:33:07.678+05:30 DEBUG 30612 --- [undedElastic-10] .s.w.r.r.m.a.ResponseEntityResultHandler : [dbb74de6-218] Using 'application/vnd.spring-boot.actuator.v3+json' given [text/plain, text/*, */*] and supported [application/vnd.spring-boot.actuator.v3+json, application/vnd.spring-boot.actuator.v2+json, application/json]
2022-12-16T11:33:07.678+05:30 DEBUG 30612 --- [undedElastic-10] .s.w.r.r.m.a.ResponseEntityResultHandler : [dbb74de6-218] 0..1 [org.springframework.boot.actuate.health.SystemHealth]
2022-12-16T11:33:07.679+05:30 DEBUG 30612 --- [undedElastic-10] o.s.http.codec.json.Jackson2JsonEncoder  : [dbb74de6-218] Encoding [org.springframework.boot.actuate.health.SystemHealth@76a8337a]
2022-12-16T11:33:07.680+05:30 DEBUG 30612 --- [ctor-http-nio-3] o.s.w.s.adapter.HttpWebHandlerAdapter    : [dbb74de6-218] Completed 503 SERVICE_UNAVAILABLE
```

**Comment by welsh** [comment]
Appears related to https://github.com/spring-cloud/spring-cloud-gateway/issues/2816

**Comment by spencergibb** [comment]
Fixed by https://github.com/spring-cloud/spring-cloud-gateway/issues/2816
