### ISSUE TITLE
If consul not available app fails to start

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-consul#81]
Allow possibly async startup (see [this 4finance PR](https://github.com/4finance/micro-infra-spring/pull/496/)) or retry w/exponential backoff. Async wouldn't work for bootstrap/config.

**Comment by spencergibb** [comment]
eureka and zookeeper have retry facilities built in.

**Comment by stefanberkner** [comment]
It is not only a problem, when consul is not available at all, but also when the consul cluster is not yet completely bootstrapped. In that case it will just quit with a exception since it cannot get the key/values (even when there are none).

```
Exception in thread "main" OperationException{statusCode=500, statusMessage='Internal Server Error'}
	at com.ecwid.consul.v1.kv.KeyValueConsulClient.getKVValues(KeyValueConsulClient.java:144)
	at com.ecwid.consul.v1.kv.KeyValueConsulClient.getKVValues(KeyValueConsulClient.java:128)
	at com.ecwid.consul.v1.ConsulClient.getKVValues(ConsulClient.java:321)
	at org.springframework.cloud.consul.config.ConsulPropertySource.init(ConsulPropertySource.java:51)
	at org.springframework.cloud.consul.config.ConsulPropertySourceLocator.locate(ConsulPropertySourceLocator.java:70)
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:85)
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:567)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
```

**Comment by denderello** [comment]
Seeing the same when trying to run `mvn package` on a fresh bootstrapped application with consul support applicated. the application does not start during the exectution of the `test` target because it cannot connect to consul.

**Comment by laurikimmel** [comment]
When using Eureka I can disable service registration by setting property `eureka.client.registerWithEureka` to `false`. For example when I'm running tests.

I was trying to do same with Consul by using property `spring.cloud.consul.discovery.enabled` (from class `ConsulDiscoveryProperties`). It's not working when Consul is not available. Still getting `com.ecwid.consul.transport.TransportException: java.net.ConnectException: Connection refused` as without setting the property to `false`.

Looks like field `ConsulDiscoveryProperties.enabled` is never used.

**Comment by denderello** [comment]
I was able to ship around this when avoiding the use of the `@Configuration` and `@EnableAutoConfiguration` annotations in my Application class (see here in my [little playground project](https://github.com/denderello/java-distributed-helloworld/blob/master/springboot-word-generator/src/main/java/com/denderello/SpringbootWordGeneratorApplication.java)). At least this with this I was able to package my applications.

**Comment by nickcodefresh** [comment]
This is also causing an issue for myself. A retry ability would be great.

**Comment by eshedly** [comment]
Hi,

I am using the sample Consul app and getting the following exception:
```
java.lang.IllegalStateException: Error processing condition on org.springframework.cloud.consul.discovery.ConsulDiscoveryClientConfiguration.consulLifecycle
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:64) ~[spring-boot-autoconfigure-1.4.0.M1.jar:1.4.0.M1]
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:102) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:178) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:140) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:116) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:333) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:243) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:273) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:98) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:678) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:520) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.4.0.M1.jar:1.4.0.M1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:768) [spring-boot-1.4.0.M1.jar:1.4.0.M1]
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:362) [spring-boot-1.4.0.M1.jar:1.4.0.M1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) [spring-boot-1.4.0.M1.jar:1.4.0.M1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1183) [spring-boot-1.4.0.M1.jar:1.4.0.M1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1172) [spring-boot-1.4.0.M1.jar:1.4.0.M1]
	at com.qucera.Pomtest5Application.main(Pomtest5Application.java:12) [classes/:na]
Caused by: java.lang.IllegalArgumentException: @ConditionalOnMissingBean annotations must specify at least one bean (type, name or annotation)
	at org.springframework.util.Assert.isTrue(Assert.java:68) ~[spring-core-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanSearchSpec.validate(OnBeanCondition.java:279) ~[spring-boot-autoconfigure-1.4.0.M1.jar:1.4.0.M1]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanSearchSpec.<init>(OnBeanCondition.java:275) ~[spring-boot-autoconfigure-1.4.0.M1.jar:1.4.0.M1]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:111) ~[spring-boot-autoconfigure-1.4.0.M1.jar:1.4.0.M1]
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47) ~[spring-boot-autoconfigure-1.4.0.M1.jar:1.4.0.M1]
	... 17 common frames omitted
```

Here is my Application.java

```
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.client.discovery.EnableDiscoveryClient;

@SpringBootApplication
@EnableDiscoveryClient
public class Pomtest5Application {

	public static void main(String[] args) {
		SpringApplication.run(Pomtest5Application.class, args);
	}
}
```

I can post my pom if needed.
Thanks

**Comment by demaniak** [comment]
@denderello could you maybe point out exactly what you did to work-a-round this issue?

**Comment by mario45211** [comment]
As far as I understand this topic there is retry behaviour, causing app to keep trying register itself to a Consul at startup, but freezing app at bootstrap phrase until success at the same time ? If I am correct, is there any way to let app starts and operates normally when Consul not available during startup, but keep retrying a register operation at background ?
